# docs 目录说明

`docs/` 是 Human Infra 的总理论和治理边界层，只保存跨子域稳定材料，不承载某个子域的业务数据或采集脚本。

## 目录结构

```text
docs/
├── AGENTS.md
├── README.md
├── decisions/
│   ├── 0001-adopt-docs-as-code-knowledge-base-structure.md
│   ├── 0002-adopt-local-quality-gates.md
│   ├── 0003-add-future-waiting-domain.md
│   ├── 0004-add-cellular-reprogramming-domain.md
│   ├── 0005-establish-research-domain-atlas.md
│   ├── 0006-add-second-wave-research-domains.md
│   ├── 0007-add-third-wave-research-domains.md
│   ├── 0008-add-fourth-wave-molecular-maintenance-domains.md
│   ├── 0009-add-fifth-wave-external-technology-risk-domains.md
│   ├── 0010-add-sixth-wave-physiological-structural-maintenance-domains.md
│   ├── 0011-add-seventh-wave-homeostasis-choice-domains.md
│   ├── 0012-add-eighth-wave-agency-task-resource-domains.md
│   ├── 0013-add-ninth-wave-service-continuity-domains.md
│   ├── 0014-add-tenth-wave-basic-livelihood-risk-transfer-domains.md
│   ├── 0015-add-eleventh-wave-civic-safety-continuity-domains.md
│   ├── 0016-add-twelfth-wave-treatment-service-rights-domains.md
│   ├── 0017-add-thirteenth-wave-health-data-outcomes-public-health-domains.md
│   ├── 0018-add-fourteenth-wave-public-services-emergency-financial-workforce-domains.md
│   ├── 0019-add-fifteenth-wave-preparedness-literacy-workforce-burden-community-data-domains.md
│   ├── 0020-add-sixteenth-wave-education-research-standards-cyber-compute-clinical-translation-domains.md
│   ├── 0021-add-seventeenth-wave-geospatial-weather-building-manufacturing-procurement-one-health-domains.md
│   ├── 0022-add-eighteenth-wave-lab-blood-waste-radiation-chemical-critical-materials-domains.md
│   ├── 0023-add-nineteenth-wave-air-food-occupational-device-sterilization-accessibility-domains.md
│   ├── 0024-add-twentieth-wave-clinical-drug-ems-surgical-road-safety-domains.md
│   ├── 0025-add-twenty-first-wave-rural-homelessness-correctional-disability-dementia-infectious-continuity-domains.md
│   ├── 0026-add-twenty-second-wave-crisis-exploitation-recovery-domains.md
│   ├── 0027-add-twenty-third-wave-complex-care-navigation-transition-decision-domains.md
│   ├── 0028-add-twenty-fourth-wave-externalized-subject-continuity-domains.md
│   ├── 0029-add-twenty-fifth-wave-civilizational-continuity-collective-security-domains.md
│   ├── 0030-add-twenty-sixth-wave-primary-production-natural-systems-logistics-domains.md
│   ├── 0031-add-twenty-seventh-wave-coastal-civil-urban-infrastructure-domains.md
│   ├── 0032-add-twenty-eighth-wave-utility-lifeline-continuity-domains.md
│   ├── 0033-add-twenty-ninth-wave-biomedical-platform-domains.md
│   ├── 0034-add-thirtieth-wave-quantitative-methodology-domains.md
│   ├── 0035-add-thirty-first-wave-knowledge-governance-technology-diffusion-domains.md
│   ├── 0036-add-thirty-second-wave-research-evidence-infrastructure-domains.md
│   ├── 0037-add-thirty-third-wave-future-technology-continuity-domains.md
│   ├── 0038-add-thirty-fourth-wave-acute-neuro-continuity-domains.md
│   ├── 0039-add-thirty-fifth-wave-sensory-communication-continuity-domains.md
│   ├── 0040-add-thirty-sixth-wave-planetary-geophysical-heat-risk-domains.md
│   ├── 0041-add-thirty-seventh-wave-chronic-environmental-exposure-domains.md
│   ├── 0042-add-thirty-eighth-wave-decision-authority-fiduciary-continuity-domains.md
│   ├── 0043-add-thirty-ninth-wave-algorithmic-access-screening-domains.md
│   ├── 0044-add-fortieth-wave-credential-licensure-continuity-domains.md
│   ├── 0045-add-forty-first-wave-income-entitlement-record-continuity-domains.md
│   ├── 0046-add-forty-second-wave-work-interruption-care-continuity-domains.md
│   ├── 0047-add-forty-third-wave-life-event-household-record-continuity-domains.md
│   ├── 0048-add-forty-fourth-wave-asset-account-transaction-continuity-domains.md
│   ├── 0049-add-forty-fifth-wave-legal-status-coercive-process-continuity-domains.md
│   ├── 0050-add-forty-sixth-wave-school-service-continuity-domains.md
│   ├── 0051-add-forty-seventh-wave-postsecondary-student-continuity-domains.md
│   ├── 0052-add-forty-eighth-wave-digital-account-continuity-domains.md
│   ├── 0053-add-forty-ninth-wave-software-device-trust-continuity-domains.md
│   ├── 0054-add-fiftieth-wave-personal-operations-continuity-domains.md
│   ├── 0055-add-fifty-first-wave-household-operations-continuity-domains.md
│   ├── 0056-add-fifty-second-wave-personal-mobility-execution-continuity-domains.md
│   ├── 0057-add-fifty-third-wave-public-realm-survival-access-continuity-domains.md
│   ├── 0058-add-fifty-fourth-wave-food-acquisition-execution-continuity-domains.md
│   ├── 0059-add-fifty-fifth-wave-treatment-execution-medical-supply-continuity-domains.md
│   ├── 0060-add-fifty-sixth-wave-outpatient-access-clinical-service-execution-domains.md
│   ├── 0061-add-fifty-seventh-wave-medical-payment-billing-cost-protection-domains.md
│   ├── 0062-add-fifty-eighth-wave-patient-rights-records-communication-domains.md
│   ├── 0063-add-fifty-ninth-wave-emergency-health-handoff-domains.md
│   ├── 0064-add-sixtieth-wave-post-death-survivor-continuity-domains.md
│   ├── 0065-add-sixty-first-wave-relational-social-capital-continuity-domains.md
│   ├── 0066-add-sixty-second-wave-meaning-culture-identity-continuity-domains.md
│   ├── 0067-add-sixty-third-wave-human-factors-operational-reliability-domains.md
│   ├── 0068-add-sixty-fourth-wave-mental-health-neurodevelopment-functioning-domains.md
│   ├── 0069-add-sixty-fifth-wave-companion-service-animal-continuity-domains.md
│   ├── 0070-add-sixty-sixth-wave-travel-lodging-border-continuity-domains.md
│   ├── 0071-add-sixty-seventh-wave-consumer-transaction-continuity-domains.md
│   ├── 0072-add-sixty-eighth-wave-consumer-credit-lending-continuity-domains.md
│   ├── 0073-add-sixty-ninth-wave-personal-insurance-claims-continuity-domains.md
│   ├── 0074-add-seventieth-wave-victim-safety-recovery-continuity-domains.md
│   ├── 0075-add-seventy-first-wave-housing-tenure-stability-continuity-domains.md
│   ├── 0076-add-seventy-second-wave-court-access-procedure-continuity-domains.md
│   ├── 0077-add-seventy-third-wave-personal-data-privacy-continuity-domains.md
│   ├── 0078-add-seventy-fourth-wave-digital-content-trust-continuity-domains.md
│   ├── 0079-add-seventy-fifth-wave-intellectual-property-digital-rights-continuity-domains.md
│   ├── 0080-add-seventy-sixth-wave-research-identity-reproducibility-infrastructure-domains.md
│   ├── 0081-add-seventy-seventh-wave-evidence-synthesis-guideline-translation-domains.md
│   ├── 0082-add-seventy-eighth-wave-research-correction-scientific-integrity-domains.md
│   ├── 0083-add-seventy-ninth-wave-ai-evaluation-operations-governance-domains.md
│   ├── 0084-add-eightieth-wave-compute-energy-connectivity-substrate-domains.md
│   ├── 0085-add-eighty-first-wave-acute-rescue-organ-support-domains.md
│   ├── 0086-add-eighty-second-wave-acute-internal-medicine-emergency-domains.md
│   ├── 0087-add-eighty-third-wave-preventive-risk-factor-control-domains.md
│   ├── 0088-add-eighty-fourth-wave-life-course-preventive-continuity-domains.md
│   ├── 0089-add-eighty-fifth-wave-chronic-specialty-burden-continuity-domains.md
│   ├── 0090-add-eighty-sixth-wave-chronic-neuro-neuromuscular-post-infectious-continuity-domains.md
│   ├── 0091-add-eighty-seventh-wave-organ-specific-cancer-continuity-domains.md
│   ├── 0092-add-eighty-eighth-wave-oral-dental-jaw-function-continuity-domains.md
│   ├── 0093-add-eighty-ninth-wave-eye-disease-visual-function-continuity-domains.md
│   ├── 0094-add-ninetieth-wave-auditory-communication-execution-continuity-domains.md
│   ├── 0095-add-ninety-first-wave-vestibular-balance-execution-continuity-domains.md
│   ├── 0096-add-ninety-second-wave-speech-language-communication-execution-domains.md
│   ├── 0097-add-ninety-third-wave-swallowing-feeding-execution-domains.md
│   ├── 0098-add-ninety-fourth-wave-urinary-renal-replacement-continuity-domains.md
│   ├── 0099-add-ninety-fifth-wave-skin-wound-barrier-continuity-domains.md
│   ├── 0100-add-ninety-sixth-wave-home-injury-domestic-safety-continuity-domains.md
│   ├── 0101-add-ninety-seventh-wave-child-recreation-injury-prevention-domains.md
│   ├── 0102-add-ninety-eighth-wave-household-personal-emergency-preparedness-domains.md
│   ├── 0103-add-ninety-ninth-wave-disaster-recovery-execution-continuity-domains.md
│   ├── 0104-add-one-hundredth-wave-infectious-disease-outbreak-response-execution-domains.md
│   ├── 0105-add-one-hundred-first-wave-hazardous-materials-industrial-incident-execution-domains.md
│   ├── 0106-establish-transcendental-domain-index.md
│   ├── 0107-add-one-hundred-second-wave-severe-weather-hazard-execution-domains.md
│   ├── 0108-add-one-hundred-third-wave-vector-animal-pest-exposure-execution-domains.md
│   ├── 0109-add-one-hundred-fourth-wave-plant-algae-fungi-outdoor-biological-exposure-domains.md
│   ├── 0110-add-one-hundred-fifth-wave-personal-device-consumable-continuity-domains.md
│   ├── 0111-add-one-hundred-sixth-wave-assistive-device-operational-continuity-domains.md
│   ├── 0112-add-one-hundred-seventh-wave-household-water-wastewater-execution-domains.md
│   ├── 0113-add-one-hundred-eighth-wave-household-energy-thermal-safety-domains.md
│   ├── 0114-add-one-hundred-ninth-wave-household-waste-disposal-execution-domains.md
│   ├── 0115-add-one-hundred-tenth-wave-household-indoor-air-ventilation-execution-domains.md
│   ├── 0116-add-one-hundred-eleventh-wave-household-physical-order-object-access-domains.md
│   ├── 0117-add-one-hundred-twelfth-wave-household-operating-metadata-handoff-domains.md
│   ├── 0118-add-one-hundred-thirteenth-wave-neighborhood-public-space-maintenance-service-request-domains.md
│   ├── 0119-add-one-hundred-fourteenth-wave-early-child-care-execution-domains.md
│   ├── 0120-add-one-hundred-fifteenth-wave-long-term-care-execution-domains.md
│   ├── 0121-add-one-hundred-sixteenth-wave-population-geographic-access-domains.md
│   ├── 0122-add-one-hundred-seventeenth-wave-transition-age-youth-domains.md
│   ├── 0123-add-one-hundred-eighteenth-wave-perinatal-continuity-domains.md
│   ├── 0124-add-one-hundred-nineteenth-wave-pediatric-prevention-screening-domains.md
│   ├── 0125-add-one-hundred-twentieth-wave-youth-online-health-platform-risk-domains.md
│   ├── 0126-add-one-hundred-twenty-first-wave-public-benefits-redetermination-domains.md
│   ├── 0127-add-one-hundred-twenty-second-wave-child-nutrition-program-execution-domains.md
│   ├── 0128-add-one-hundred-twenty-third-wave-food-is-medicine-execution-domains.md
│   ├── 0129-add-one-hundred-twenty-fourth-wave-reproductive-technology-governance-domains.md
│   ├── 0130-add-one-hundred-twenty-fifth-wave-longevity-intervention-governance-domains.md
│   ├── 0131-add-one-hundred-twenty-sixth-wave-reproductive-endocrine-pelvic-function-domains.md
│   ├── 0132-add-one-hundred-twenty-seventh-wave-endocrine-feedback-axis-domains.md
│   ├── 0133-add-one-hundred-twenty-eighth-wave-sleep-wake-scheduling-domains.md
│   ├── 0134-add-one-hundred-twenty-ninth-wave-workplace-safety-execution-domains.md
│   ├── 0135-add-one-hundred-thirtieth-wave-construction-industrial-fatal-hazard-domains.md
│   ├── 0136-add-one-hundred-thirty-first-wave-immune-aging-systemic-signal-domains.md
│   ├── 0137-add-one-hundred-thirty-second-wave-intracellular-quality-control-molecular-maintenance-domains.md
│   ├── 0138-add-one-hundred-thirty-third-wave-organelle-homeostasis-spatial-stress-domains.md
│   ├── 0139-add-synthetic-biological-intelligence-organoid-computing-domain.md
│   └── README.md
├── explanations/
│   ├── README.md
│   ├── effective-immortality-acceleration-flywheel.md
│   ├── human-runtime-infrastructure.md
│   ├── life-path-prediction-model.md
│   ├── noah-ark-genealogy.md
│   └── value-lenses.md
├── how-to/
│   ├── README.md
│   ├── add-domain.md
│   ├── add-source-note.md
│   ├── contribute-docs.md
│   ├── run-quality-checks.md
│   └── share-human-infra.md
├── reference/
│   ├── README.md
│   ├── applications-and-literature.md
│   ├── document-lifecycle.md
│   ├── domain-map.md
│   ├── evidence-policy.md
│   ├── ethics-and-safety-boundaries.md
│   ├── glossary.md
│   ├── life-path-prediction-model-contract.md
│   ├── life-path-prediction-model-governance.md
│   ├── project-boundary-v0.1.md
│   ├── repository-standards.md
│   ├── transcendental-domain-index.md
│   ├── research-domain-atlas.md
│   ├── research-domain-radar.md
│   ├── research-model-visualization-toolkit.md
│   ├── review-checklists.md
│   ├── source-card-system.md
│   ├── source-management.md
│   └── writing-style-guide.md
├── source-notes/
│   ├── README.md
│   ├── core-literature/
│   │   ├── AGENTS.md
│   │   ├── README.md
│   │   ├── reading-reports/
│   │   ├── 2026-06-28-human-infra-core-12-source-card-pack.md
│   │   └── 2026-06-28-human-infra-genealogy-download-manifest.md
│   ├── disembodied-cns-and-memory-editing-brief.md
│   ├── 2026-06-29-metric-redshift-recursive-waiting-revision-notes.md
│   ├── 2026-06-28-effective-immortality-flywheel-automated-research-run.md
│   ├── 2026-06-28-effective-immortality-flywheel-derivation-package.md
│   ├── 2026-06-28-effective-immortality-flywheel-evidence-matrix.md
│   ├── 2026-06-28-effective-immortality-flywheel-source-cards.md
│   ├── disembodied-cns-interface-architecture.md
│   ├── human-runtime-infrastructure-learning-note.md
│   └── human-runtime-infrastructure-longform.md
├── templates/
│   ├── README.md
│   ├── decision-record.md
│   ├── domain-readme.md
│   ├── research-card.md
│   ├── reference-doc.md
│   └── source-note.md
└── tutorials/
```

## 文件职责

- `explanations/human-runtime-infrastructure.md`：定义 Human Infra 的核心模型、七层结构、诊断框架和 Human SRE 类比。
- `explanations/effective-immortality-acceleration-flywheel.md`：新建有效永生飞轮 working paper，定义主体持续时间、有效时间、学习轮次、积累资本、技术采用、行动质量和可能性空间之间的研究链路。
- `explanations/life-path-prediction-model.md`：解释定量生命路径预测层的概念、时间类型、模型族和边界。
- `explanations/noah-ark-genealogy.md`：定义“诺亚方舟”作为 Human Infra 主隐喻的叙事谱系、理论谱系、映射、使用场景和传播边界。
- `explanations/value-lenses.md`：定义 Human Infra 的多视角价值理解，补充“寿命延长和逃逸路径带来的通用资源预算增量”视角但不替代主体持续性主线。
- `reference/applications-and-literature.md`：整理 Human Infra 的真实应用案例和首批文献主干。
- `reference/life-path-prediction-model-contract.md`：定义干预、状态转移、风险函数、生存曲线、有效时间、主观时间、相对时间和未来选择权的预测模型契约。
- `reference/life-path-prediction-model-governance.md`：定义定量预测模型的证据准入、偏差审查、验证、报告和禁止用途门禁。
- `reference/project-boundary-v0.1.md`：定义当前公开版本边界、纳入范围、排除范围、材料落点和后续版本方向。
- `reference/transcendental-domain-index.md`：把“有效永生何以可能”的先验追问压缩成 A-K 主干研究域入口。
- `reference/research-domain-atlas.md`：定义从有效永生先验条件生成研究域的规则、当前域地图和域判定契约。
- `reference/research-domain-radar.md`：记录尚未晋升为正式子域的潜在研究域、来源信号和晋升触发条件。
- `reference/domain-map.md`、`reference/research-domain-atlas.md`、`reference/research-domain-radar.md`、`reference/applications-and-literature.md` 和 `reference/ethics-and-safety-boundaries.md`：同时索引细胞内质量控制与分子信息维护域，覆盖溶酶体通量、蛋白周转、翻译保真、RNA 维护、核质运输和铁死亡膜韧性。
- `reference/domain-map.md`、`reference/research-domain-atlas.md`、`reference/research-domain-radar.md`、`reference/applications-and-literature.md` 和 `reference/ethics-and-safety-boundaries.md`：同时索引细胞器稳态、空间组织与应激响应域，覆盖 ER stress/UPR、Golgi、peroxisome、organelle contact sites、biomolecular condensates 和 mechanotransduction。
- `domains/c4-conversion-channel/health-data-privacy-governance/`、`domains/c4-conversion-channel/functioning-quality-of-life-outcomes/`、`domains/c6-local-unlocking/health-economics-value-assessment/`、`domains/c2-source-maintenance/immunization-public-health-surveillance/`、`domains/c2-source-maintenance/maternal-newborn-child-development/` 和 `domains/c2-source-maintenance/patient-safety-organizational-learning/`：第十三波正式研究域，分别承载数据治理、结局评估、价值评估、公共卫生监测、早期生命基础设施和患者安全组织学习。
- `domains/c5-ecological-substrate/social-determinants-community-vulnerability/`、`domains/c5-ecological-substrate/public-service-design-accessibility/`、`domains/c5-ecological-substrate/emergency-alerts-communications/`、`domains/c5-ecological-substrate/disaster-recovery-relief-continuity/`、`domains/c5-ecological-substrate/financial-inclusion-payment-systems/` 和 `domains/c5-ecological-substrate/workforce-employment-services/`：第十四波正式研究域，分别承载社会决定因素、公共服务设计、应急预警通信、灾后恢复、金融支付入口和就业服务。
- `domains/c5-ecological-substrate/household-emergency-preparedness-resilience/`、`domains/c3-generation-engine/media-information-literacy-public-libraries/`、`domains/c3-generation-engine/health-workforce-capacity/`、`domains/c4-conversion-channel/administrative-burden-procedural-friction/`、`domains/c4-conversion-channel/community-health-workers-peer-support/` 和 `domains/c5-ecological-substrate/civic-data-open-government-transparency/`：第十五波正式研究域，分别承载家庭准备、信息素养与公共图书馆、健康劳动力容量、行政负担、社区中介支持和开放政府透明。
- `domains/c3-generation-engine/education-access-lifelong-learning/`、`domains/c4-conversion-channel/research-infrastructure-open-science-translation/`、`domains/c4-conversion-channel/standards-metrology-quality-infrastructure/`、`domains/c5-ecological-substrate/cybersecurity-resilience-critical-services/`、`domains/c3-generation-engine/compute-data-center-ai-infrastructure/` 和 `domains/c4-conversion-channel/clinical-trials-regulatory-science-translation/`：第十六波正式研究域，分别承载教育终身学习、科研开放转化、标准计量质量、网络安全韧性、算力 AI 基础设施和临床监管转化。
- `domains/c4-conversion-channel/geospatial-navigation-location-infrastructure/`、`domains/c5-ecological-substrate/weather-climate-observation-forecasting/`、`domains/c6-local-unlocking/building-fire-life-safety-codes/`、`domains/c6-local-unlocking/manufacturing-repair-capacity/`、`domains/c4-conversion-channel/public-procurement-contracting-capacity/` 和 `domains/c6-local-unlocking/animal-health-zoonotic-interface-one-health/`：第十七波正式研究域，分别承载空间定位导航、天气气候观测预报、建筑消防生命安全、制造维修能力、公共采购合同能力和动物健康 One Health 界面。
- `domains/c6-local-unlocking/human-animal-bond-companion-care-continuity/`、`domains/c6-local-unlocking/veterinary-care-access-cost-continuity/`、`domains/c6-local-unlocking/service-animal-disability-access-continuity/`、`domains/c6-local-unlocking/pet-identification-microchip-reunification-continuity/`、`domains/c5-ecological-substrate/pet-food-medication-supply-safety-continuity/`、`domains/c5-ecological-substrate/pet-disaster-evacuation-sheltering-continuity/`、`domains/c6-local-unlocking/animal-shelter-rescue-rehoming-continuity/` 和 `domains/c6-local-unlocking/animal-welfare-cruelty-reporting-continuity/`：第六十五波正式研究域，分别承载人-动物纽带/伴侣照护、兽医可及费用、服务动物残障可达、宠物身份微芯片重聚、宠物食药供应安全、宠物灾害撤离避难、动物收容救助再安置和动物福利虐待报告。
- `domains/c6-local-unlocking/long-distance-travel-booking-itinerary-continuity/`、`domains/c3-generation-engine/air-passenger-rights-disruption-refund-continuity/`、`domains/c4-conversion-channel/aviation-security-screening-identity-continuity/`、`domains/c3-generation-engine/baggage-personal-property-travel-continuity/`、`domains/c6-local-unlocking/lodging-temporary-accommodation-access-continuity/`、`domains/c6-local-unlocking/travel-advisory-consular-assistance-continuity/`、`domains/c6-local-unlocking/travel-health-preparedness-continuity/` 和 `domains/c6-local-unlocking/customs-border-entry-declaration-continuity/`：第六十六波正式研究域，分别承载长距离旅行预订行程、航空旅客权利/中断退款、航空安检身份核验、行李个人物品、临时住宿接入、旅行警示领事协助、旅行健康准备和海关边境入境申报。
- `domains/c6-local-unlocking/online-retail-order-shipping-fulfillment-continuity/`、`domains/c6-local-unlocking/consumer-return-refund-dispute-resolution-continuity/`、`domains/c5-ecological-substrate/consumer-warranty-service-contract-repair-continuity/`、`domains/c6-local-unlocking/right-to-repair-parts-manuals-access-continuity/`、`domains/c5-ecological-substrate/payment-card-dispute-unauthorized-charge-continuity/`、`domains/c6-local-unlocking/gift-card-prepaid-stored-value-continuity/`、`domains/c6-local-unlocking/price-fee-disclosure-junk-fee-continuity/` 和 `domains/c4-conversion-channel/consumer-reviews-endorsements-marketplace-trust-continuity/`：第六十七波正式研究域，分别承载在线零售订单履约、消费者退货退款争议、消费品保修维修、维修权零件手册、支付卡争议未授权扣款、礼品卡预付储值、价格费用披露和消费者评价背书市场信任。
- `domains/c6-local-unlocking/credit-card-revolving-credit-cost-continuity/`、`domains/c6-local-unlocking/consumer-loan-origination-apr-disclosure-continuity/`、`domains/c6-local-unlocking/mortgage-origination-servicing-foreclosure-continuity/`、`domains/c6-local-unlocking/auto-loan-lease-servicing-repossession-continuity/`、`domains/c6-local-unlocking/student-loan-servicing-repayment-forgiveness-continuity/`、`domains/c6-local-unlocking/payday-small-dollar-title-loan-continuity/`、`domains/c6-local-unlocking/buy-now-pay-later-installment-financing-continuity/` 和 `domains/c6-local-unlocking/remittance-money-transfer-disclosure-continuity/`：第六十八波正式研究域，分别承载信用卡循环信用成本、消费贷款 APR 披露、房贷服务止赎、车贷租赁收车、学生贷款还款减免、发薪日小额高成本贷款、BNPL 分期融资和汇款转账费用汇率披露。
- `domains/c5-ecological-substrate/auto-insurance-liability-collision-claims-continuity/`、`domains/c5-ecological-substrate/homeowners-renters-property-insurance-claims-continuity/`、`domains/c5-ecological-substrate/flood-insurance-nfip-claims-continuity/`、`domains/c5-ecological-substrate/catastrophe-wind-wildfire-earthquake-insurance-continuity/`、`domains/c5-ecological-substrate/disability-income-insurance-claim-continuity/`、`domains/c4-conversion-channel/long-term-care-insurance-benefit-activation-continuity/`、`domains/c5-ecological-substrate/travel-insurance-trip-protection-claims-continuity/` 和 `domains/c3-generation-engine/personal-liability-umbrella-insurance-defense-continuity/`：第六十九波正式研究域，分别承载汽车保险责任碰撞理赔、房主租客财产理赔、洪水/NFIP 理赔、风暴野火地震巨灾保险、残障收入保险理赔、长期照护福利启动、旅行保险行程保护理赔和个人责任伞形保险防御。
- `domains/c6-local-unlocking/domestic-violence-coercive-control-safety-continuity/`、`domains/c6-local-unlocking/sexual-assault-forensic-exam-advocacy-continuity/`、`domains/c6-local-unlocking/stalking-harassment-protection-order-continuity/`、`domains/c6-local-unlocking/victim-witness-rights-notification-continuity/`、`domains/c6-local-unlocking/crime-victim-compensation-restitution-continuity/`、`domains/c5-ecological-substrate/survivor-safe-housing-emergency-transfer-continuity/`、`domains/c6-local-unlocking/human-trafficking-victim-identification-services-continuity/` 和 `domains/c6-local-unlocking/missing-persons-unidentified-remains-resolution-continuity/`：第七十波正式研究域，分别承载家庭暴力/胁迫控制安全、性暴力 forensic exam 与 advocacy、跟踪骚扰保护令、受害者/证人权利通知、犯罪受害者补偿与 restitution、幸存者安全住所 emergency transfer、人口贩运受害者识别服务和失踪人员/无名遗体身份恢复。
- `domains/c5-ecological-substrate/rental-lease-tenancy-rights-continuity/`、`domains/c5-ecological-substrate/eviction-prevention-court-diversion-continuity/`、`domains/c5-ecological-substrate/emergency-rental-assistance-arrears-continuity/`、`domains/c4-conversion-channel/housing-choice-voucher-public-housing-continuity/`、`domains/c5-ecological-substrate/fair-housing-discrimination-reasonable-accommodation-continuity/`、`domains/c5-ecological-substrate/housing-habitability-inspection-code-enforcement-continuity/`、`domains/c4-conversion-channel/hud-approved-housing-counseling-navigation-continuity/` 和 `domains/c5-ecological-substrate/manufactured-housing-park-tenure-safety-continuity/`：第七十一波正式研究域，分别承载租赁租约居住权、驱逐预防法院 diversion、应急租金援助与欠租、住房选择券/公屋、公平住房/合理便利、住房可居住性检查 code enforcement、HUD 批准住房咨询和制造房屋园区 tenure 安全。
- `domains/c5-ecological-substrate/self-represented-litigant-court-self-help-continuity/`、`domains/c5-ecological-substrate/court-efiling-document-submission-continuity/`、`domains/c2-source-maintenance/remote-hybrid-court-hearing-access-continuity/`、`domains/c3-generation-engine/court-language-access-interpreter-continuity/`、`domains/c5-ecological-substrate/court-disability-accommodation-accessibility-continuity/`、`domains/c5-ecological-substrate/court-fees-fines-ability-to-pay-continuity/`、`domains/c6-local-unlocking/jury-service-summons-hardship-continuity/` 和 `domains/c6-local-unlocking/small-claims-civil-dispute-resolution-continuity/`：第七十二波正式研究域，分别承载自行诉讼人自助、法院电子 filing、远程/混合 hearing、法院语言服务、法院残障便利、法院罚金费用支付能力、陪审传票 hardship 和小额民事纠纷恢复。
- `domains/c4-conversion-channel/data-broker-registry-opt-out-deletion-continuity/`、`domains/c4-conversion-channel/privacy-rights-access-correction-deletion-continuity/`、`domains/c6-local-unlocking/opt-out-preference-signal-consent-revocation-continuity/`、`domains/c6-local-unlocking/commercial-surveillance-adtech-profile-continuity/`、`domains/c4-conversion-channel/sensitive-location-data-exposure-continuity/`、`domains/c6-local-unlocking/biometric-identifier-template-governance-continuity/`、`domains/c4-conversion-channel/children-teen-data-privacy-consent-continuity/` 和 `domains/c4-conversion-channel/data-breach-notification-identity-recovery-continuity/`：第七十三波正式研究域，分别承载数据经纪登记/退出/删除、隐私权访问更正删除、退出偏好信号与同意撤回、商业监控广告画像、敏感位置数据、生物特征模板治理、儿童青少年数据隐私和数据泄露通知身份恢复。
- `domains/c6-local-unlocking/youth-social-media-mental-health-continuity/`、`domains/c6-local-unlocking/youth-online-safety-by-design-platform-governance-continuity/`、`domains/c6-local-unlocking/cyberbullying-online-harassment-reporting-continuity/`、`domains/c6-local-unlocking/online-child-sexual-exploitation-sextortion-reporting-continuity/`、`domains/c6-local-unlocking/gaming-loot-box-inapp-purchase-dark-pattern-continuity/` 和 `domains/c6-local-unlocking/child-stealth-advertising-influencer-marketing-continuity/`：第一百二十波正式研究域，分别承载青少年社交媒体心理健康、青少年线上安全设计与平台治理、网络霸凌在线骚扰举报、儿童线上性剥削与 sextortion 举报、游戏内购/loot box/暗黑模式和儿童隐性广告/网红营销连续性。
- `domains/c4-conversion-channel/snap-eligibility-recertification-abawd-continuity/`、`domains/c6-local-unlocking/medicaid-chip-renewal-redetermination-continuity/`、`domains/c5-ecological-substrate/medicare-enrollment-coverage-transition-continuity/`、`domains/c4-conversion-channel/ssi-ssdi-disability-review-appeal-continuity/`、`domains/c6-local-unlocking/tanf-cash-assistance-work-support-continuity/` 和 `domains/c4-conversion-channel/unemployment-insurance-claim-appeal-identity-continuity/`：第一百二十一波正式研究域，分别承载 SNAP 资格续期/ABAWD/E&T、Medicaid/CHIP 续期重判、Medicare 覆盖转换、SSI/SSDI 复审申诉、TANF 现金援助工作支持和失业保险申领/身份核验/申诉支付连续性。
- `domains/c3-generation-engine/content-provenance-authenticity-credential-continuity/`、`domains/c2-source-maintenance/synthetic-media-watermarking-disclosure-continuity/`、`domains/c3-generation-engine/ai-impersonation-deepfake-fraud-continuity/`、`domains/c6-local-unlocking/voice-call-caller-id-authentication-continuity/`、`domains/c6-local-unlocking/email-domain-authentication-spoofing-continuity/`、`domains/c6-local-unlocking/official-web-domain-brand-impersonation-continuity/`、`domains/c4-conversion-channel/digital-evidence-preservation-chain-of-custody-continuity/` 和 `domains/c6-local-unlocking/platform-content-moderation-notice-appeal-continuity/`：第七十四波正式研究域，分别承载内容来源凭据、合成媒体水印披露、AI 冒充 deepfake fraud、电话 caller ID 认证、邮件域名认证、官网品牌冒充、数字证据保存链和平台内容审核通知申诉。
- `domains/c6-local-unlocking/copyright-authorship-registration-licensing-continuity/`、`domains/c6-local-unlocking/dmca-notice-counter-notice-platform-removal-continuity/`、`domains/c6-local-unlocking/creative-commons-open-content-license-continuity/`、`domains/c4-conversion-channel/open-source-software-license-compliance-continuity/`、`domains/c4-conversion-channel/trademark-brand-identity-rights-continuity/`、`domains/c6-local-unlocking/patent-invention-disclosure-maintenance-continuity/`、`domains/c4-conversion-channel/creator-royalty-rights-metadata-continuity/` 和 `domains/c3-generation-engine/ai-training-data-rights-opt-out-provenance-continuity/`：第七十五波正式研究域，分别承载版权作者身份登记许可、DMCA 通知反通知、Creative Commons 开放内容、开源软件许可证、商标品牌身份、专利发明披露维护、创作者版税权利元数据和 AI 训练数据权利/退出/provenance。
- `domains/c4-conversion-channel/scholarly-identity-orcid-affiliation-continuity/`、`domains/c4-conversion-channel/persistent-identifier-doi-citation-metadata-continuity/`、`domains/c4-conversion-channel/research-data-repository-fair-sharing-continuity/`、`domains/c4-conversion-channel/research-software-capsule-reproducibility-continuity/`、`domains/c4-conversion-channel/preregistration-registered-report-study-plan-continuity/`、`domains/c4-conversion-channel/lab-notebook-protocol-versioning-continuity/`、`domains/c6-local-unlocking/contributor-role-authorship-attribution-continuity/`、`domains/c5-ecological-substrate/conflict-of-interest-funding-disclosure-continuity/` 和 `domains/c4-conversion-channel/research-artifact-archive-retention-preservation-continuity/`：第七十六波正式研究域，分别承载科研身份、持久标识、研究数据仓库、研究软件胶囊、预注册研究计划、实验协议版本、贡献者角色、利益冲突披露和研究产物保存。
- `domains/c4-conversion-channel/systematic-review-protocol-search-screening-continuity/`、`domains/c4-conversion-channel/risk-of-bias-critical-appraisal-continuity/`、`domains/c4-conversion-channel/meta-analysis-effect-size-heterogeneity-continuity/`、`domains/c4-conversion-channel/publication-reporting-bias-detection-continuity/`、`domains/c4-conversion-channel/evidence-certainty-grade-summary-findings-continuity/`、`domains/c4-conversion-channel/evidence-to-decision-guideline-panel-continuity/`、`domains/c4-conversion-channel/guideline-appraisal-adaptation-localization-continuity/`、`domains/c4-conversion-channel/living-evidence-surveillance-update-continuity/` 和 `domains/c4-conversion-channel/rapid-review-emergency-evidence-triage-continuity/`：第七十七波正式研究域，分别承载系统综述协议/检索/筛选、风险偏倚与批判性评价、Meta 分析与异质性、发表/报告偏倚、GRADE 证据确定性、证据到决策、指南评价/适配/本地化、活证据监测更新和快速综述/紧急证据分诊。
- `domains/c4-conversion-channel/research-misconduct-investigation-correction-continuity/`、`domains/c6-local-unlocking/retraction-expression-concern-correction-continuity/`、`domains/c4-conversion-channel/preprint-versioning-public-review-continuity/`、`domains/c4-conversion-channel/journal-editorial-policy-peer-review-integrity-continuity/`、`domains/c6-local-unlocking/predatory-publishing-paper-mill-detection-continuity/`、`domains/c4-conversion-channel/citation-network-claim-propagation-continuity/`、`domains/c4-conversion-channel/research-metrics-incentives-assessment-continuity/`、`domains/c6-local-unlocking/replication-reproducibility-many-labs-continuity/` 和 `domains/c3-generation-engine/science-communication-evidence-translation-continuity/`：第七十八波正式研究域，分别承载科研不端调查纠错、撤稿/表达关注/更正、预印本版本与公开评审、期刊编辑与同行评审完整性、掠夺性出版与 paper mill 检测、引用网络主张传播、科研指标激励、复制/复现/多实验室验证和科学传播证据转译。
- `domains/c4-conversion-channel/public-health-laboratory-diagnostic-capacity/`、`domains/c2-source-maintenance/blood-organ-tissue-biovigilance-transplantation/`、`domains/c6-local-unlocking/waste-management-hazardous-materials-continuity/`、`domains/c2-source-maintenance/radiation-nuclear-safety-protection/`、`domains/c6-local-unlocking/chemical-safety-poison-control-toxicology/` 和 `domains/c5-ecological-substrate/critical-minerals-materials-resilience/`：第十八波正式研究域，分别承载公共卫生实验室诊断能力、血液器官组织生物警戒、废弃物危险材料连续性、辐射核安全防护、化学安全中毒控制和关键矿物材料韧性。
- `domains/c3-generation-engine/air-quality-ventilation-exposure-control/`、`domains/c5-ecological-substrate/food-safety-contamination-control/`、`domains/c6-local-unlocking/occupational-exposure-industrial-hygiene/`、`domains/c6-local-unlocking/medical-device-equipment-safety-maintenance/`、`domains/c2-source-maintenance/sterilization-disinfection-infection-control/` 和 `domains/c5-ecological-substrate/built-environment-accessibility-universal-design/`：第十九波正式研究域，分别承载空气质量通风暴露控制、食品安全污染控制、职业暴露工业卫生、医疗设备安全维护、灭菌消毒感染控制和建成环境无障碍通用设计。
- `domains/c4-conversion-channel/clinical-laboratory-diagnostic-quality/`、`domains/c4-conversion-channel/pharmacovigilance-drug-safety-monitoring/`、`domains/c4-conversion-channel/pharmaceutical-quality-supply-integrity/`、`domains/c5-ecological-substrate/emergency-medical-services-prehospital-care/`、`domains/c6-local-unlocking/surgical-anesthesia-perioperative-safety/` 和 `domains/c6-local-unlocking/road-traffic-injury-prevention-safe-mobility/`：第二十波正式研究域，分别承载临床检验诊断质量、药物警戒药品安全、药品质量供应完整性、急救医疗服务院前照护、手术麻醉围手术期安全和道路交通伤害预防。
- `domains/c5-ecological-substrate/rural-health-access-geographic-equity/`、`domains/c5-ecological-substrate/homelessness-unsheltered-health-continuity/`、`domains/c5-ecological-substrate/correctional-health-reentry-continuity/`、`domains/c6-local-unlocking/disability-services-independent-living/`、`domains/c3-generation-engine/dementia-cognitive-decline-care-continuity/` 和 `domains/c6-local-unlocking/chronic-infectious-disease-care-continuity/`：第二十一波正式研究域，分别承载农村健康可及、无家可归健康连续性、羁押重返健康连续性、残障独立生活、痴呆认知衰退照护和慢性传染病照护连续性。
- `domains/c6-local-unlocking/suicide-crisis-response-continuity/`、`domains/c6-local-unlocking/substance-use-treatment-recovery-continuity/`、`domains/c5-ecological-substrate/elder-justice-adult-protective-services/`、`domains/c6-local-unlocking/child-protection-family-safety/`、`domains/c6-local-unlocking/fraud-scams-consumer-protection/` 和 `domains/c6-local-unlocking/online-safety-digital-harm-prevention/`：第二十二波正式研究域，分别承载自杀危机响应、物质使用障碍治疗恢复、老年正义成人保护、儿童保护家庭安全、诈骗消费者保护和在线数字伤害预防。
- `domains/c6-local-unlocking/rare-disease-diagnostic-odyssey-care-coordination/`、`domains/c6-local-unlocking/multimorbidity-polypharmacy-care-coordination/`、`domains/c5-ecological-substrate/care-transitions-discharge-continuity/`、`domains/c5-ecological-substrate/home-health-hospice-palliative-care-continuity/`、`domains/c6-local-unlocking/medical-interpreter-cultural-mediation/` 和 `domains/c4-conversion-channel/patient-advocacy-shared-decision-making/`：第二十三波正式研究域，分别承载罕见病诊断漫游、多病共存多重用药、照护转移出院连续性、居家/缓和/安宁疗护连续性、医疗解释文化中介和患者倡导共同决策。
- `domains/c3-generation-engine/life-logging-personal-archives-continuity/`、`domains/c4-conversion-channel/digital-legacy-data-succession/`、`domains/c3-generation-engine/wearables-continuous-sensing-personal-informatics/`、`domains/c3-generation-engine/personal-knowledge-management-cognitive-offloading/`、`domains/c2-source-maintenance/brain-computer-interface-neurotechnology-governance/` 和 `domains/c3-generation-engine/robotics-embodied-assistance-care-automation/`：第二十四波正式研究域，分别承载生命日志个人档案、数字遗产继承、可穿戴连续感知、个人知识管理认知卸载、脑机接口神经技术治理和机器人具身辅助。
- `domains/c5-ecological-substrate/armed-conflict-civilian-protection-ihl/`、`domains/c5-ecological-substrate/peacebuilding-conflict-prevention-social-cohesion/`、`domains/c5-ecological-substrate/continuity-of-government-public-administration-resilience/`、`domains/c5-ecological-substrate/telecommunications-network-resilience-continuity/`、`domains/c5-ecological-substrate/macroeconomic-monetary-fiscal-stability/` 和 `domains/c5-ecological-substrate/anti-corruption-public-integrity-accountability/`：第二十五波正式研究域，分别承载武装冲突平民保护、和平建设冲突预防、政府连续性、电信网络韧性、宏观稳定和公共廉洁问责。
- `domains/c5-ecological-substrate/agricultural-production-food-system-resilience/`、`domains/c5-ecological-substrate/soil-health-land-degradation-drought-resilience/`、`domains/c5-ecological-substrate/water-resources-hydrology-flood-drought-management/`、`domains/c5-ecological-substrate/biodiversity-ecosystem-services-resilience/`、`domains/c5-ecological-substrate/wildfire-landscape-fire-resilience/` 和 `domains/c5-ecological-substrate/freight-logistics-port-cold-chain-continuity/`：第二十六波正式研究域，分别承载农业生产、土壤土地旱灾韧性、水资源水文洪旱管理、生物多样性生态服务、野火景观韧性和货运港口冷链连续性。
- `domains/c5-ecological-substrate/coastal-marine-resilience-blue-economy-continuity/`、`domains/c5-ecological-substrate/fisheries-aquatic-food-systems-continuity/`、`domains/c5-ecological-substrate/dams-levees-flood-control-infrastructure-safety/`、`domains/c4-conversion-channel/public-works-civil-infrastructure-asset-management/`、`domains/c5-ecological-substrate/urban-planning-land-use-zoning-resilience/` 和 `domains/c5-ecological-substrate/green-blue-infrastructure-urban-nature-cooling/`：第二十七波正式研究域，分别承载海岸海洋蓝色经济、水生食物系统、防洪工程资产、公共工程资产管理、城市土地使用规划和城市绿蓝基础设施。
- `domains/c5-ecological-substrate/electric-grid-reliability-resilience-continuity/`、`domains/c5-ecological-substrate/water-wastewater-utility-service-continuity/`、`domains/c5-ecological-substrate/fuel-thermal-energy-service-continuity/`、`domains/c5-ecological-substrate/public-transit-service-operations-continuity/`、`domains/c5-ecological-substrate/critical-infrastructure-lifeline-interdependency-resilience/` 和 `domains/c5-ecological-substrate/utility-affordability-shutoff-protection-continuity/`：第二十八波正式研究域，分别承载电网可靠性、水务污水公用事业、燃料热能服务、公共交通运营、关键基础设施生命线互依赖和公用事业可负担性断供保护。
- `domains/c6-local-unlocking/gene-therapy-genome-editing-delivery-safety/`、`domains/c2-source-maintenance/biological-age-clocks-biomarker-validation/`、`domains/c3-generation-engine/multiomics-personal-baseline-systems-biology/`、`domains/c2-source-maintenance/engineered-cell-therapy-regenerative-platforms/`、`domains/c2-source-maintenance/organoids-organ-on-chip-disease-models/` 和 `domains/c2-source-maintenance/xenotransplantation-bioengineered-organ-replacement/`：第二十九波正式研究域，分别承载基因治疗与基因编辑递送安全、生物年龄钟验证、多组学个人基线、工程细胞疗法、类器官组织芯片模型和异种移植工程器官替换。
- `domains/c2-source-maintenance/synthetic-biological-intelligence-organoid-computing-continuity/`：承载 SBI/OI/BI、DishBrain、CL API、体外神经网络、脑类器官、闭环反馈学习和 agency / sentience 术语治理。
- `domains/c4-conversion-channel/geroprotective-drug-repurposing-trial-governance-continuity/`、`domains/c4-conversion-channel/dietary-supplement-nutraceutical-evidence-safety-continuity/`、`domains/c2-source-maintenance/resistance-training-muscle-strength-sarcopenia-continuity/`、`domains/c2-source-maintenance/cardiorespiratory-fitness-vo2max-aerobic-capacity-continuity/`、`domains/c5-ecological-substrate/caloric-restriction-fasting-energy-balance-governance-continuity/` 和 `domains/c6-local-unlocking/thermal-stress-sauna-cold-exposure-hormesis-governance-continuity/`：第一百二十五波正式研究域，分别承载 geroprotective 药物再利用试验治理、补剂证据安全、抗阻训练肌力肌少症、心肺适能 VO2max、热量限制禁食能量平衡和冷热应激 hormesis 治理。
- `domains/c6-local-unlocking/thymic-involution-naive-t-cell-output-continuity/`、`domains/c2-source-maintenance/immune-repertoire-vaccine-response-aging-continuity/`、`domains/c6-local-unlocking/clonal-hematopoiesis-chip-inflammatory-risk-continuity/`、`domains/c6-local-unlocking/inflammaging-chronic-low-grade-inflammation-continuity/`、`domains/c6-local-unlocking/plasma-proteome-systemic-aging-signal-continuity/` 和 `domains/c6-local-unlocking/extracellular-vesicle-sasp-intercellular-aging-continuity/`：第一百三十一波正式研究域，分别承载胸腺退化/初始 T 细胞输出、免疫库/疫苗响应老化、克隆性造血/CHIP 炎症风险、炎症衰老、血浆蛋白组系统性衰老信号和 EV/SASP 细胞间衰老通讯。
- `domains/c2-source-maintenance/polycystic-ovary-syndrome-metabolic-reproductive-continuity/`、`domains/c2-source-maintenance/endometriosis-pelvic-pain-fertility-continuity/`、`domains/c2-source-maintenance/uterine-fibroids-bleeding-anemia-fertility-continuity/`、`domains/c6-local-unlocking/male-factor-infertility-sperm-health-continuity/`、`domains/c2-source-maintenance/erectile-dysfunction-vascular-sexual-function-continuity/` 和 `domains/c2-source-maintenance/vulvovaginal-pain-infection-sexual-function-continuity/`：第一百二十六波正式研究域，分别承载 PCOS/代谢生殖、内异症/盆腔痛生育、肌瘤/出血贫血生育、男性因素不育/精子健康、ED/血管性功能和外阴阴道疼痛/感染/性功能连续性。
- `domains/c4-conversion-channel/causal-inference-target-trial-emulation/`、`domains/c4-conversion-channel/survival-analysis-healthspan-risk-modeling/`、`domains/c4-conversion-channel/human-digital-twin-life-course-simulation/`、`domains/c4-conversion-channel/implementation-science-adherence-behavior-change/`、`domains/c4-conversion-channel/uncertainty-quantification-model-calibration/` 和 `domains/c4-conversion-channel/data-quality-missingness-representativeness/`：第三十波正式研究域，分别承载因果推断与目标试验模拟、生存分析与健康寿命风险建模、人类数字孪生生命历程仿真、实施科学与依从行为改变、不确定性量化与模型校准、数据质量缺失代表性审查。
- `domains/c4-conversion-channel/privacy-preserving-computation-federated-learning/`、`domains/c4-conversion-channel/knowledge-graph-ontology-semantic-interoperability/`、`domains/c4-conversion-channel/model-cards-ai-audit-documentation/`、`domains/c4-conversion-channel/technology-foresight-horizon-scanning/`、`domains/c4-conversion-channel/research-portfolio-prioritization-funding-governance/` 和 `domains/c4-conversion-channel/intellectual-property-technology-transfer-access/`：第三十一波正式研究域，分别承载隐私保护计算、知识图谱本体语义互操作、模型卡 AI 审计文档、技术预见地平线扫描、研究组合资金治理和知识产权技术转移可及。
- `domains/c4-conversion-channel/trustworthy-scientific-communication-peer-review/`、`domains/c4-conversion-channel/research-participant-consent-community-engagement/`、`domains/c4-conversion-channel/biobanking-biospecimen-quality-chain-of-custody/`、`domains/c4-conversion-channel/longitudinal-cohort-retention-followup-infrastructure/`、`domains/c4-conversion-channel/registries-real-world-data-governance/` 和 `domains/c4-conversion-channel/scientific-instrumentation-sensor-calibration-maintenance/`：第三十二波正式研究域，分别承载可信科研传播与同行评审、研究参与者同意与社区参与、生物样本库保管链、纵向队列随访、登记与真实世界数据治理和科研仪器传感器校准维护。
- `domains/c6-local-unlocking/nanomedicine-targeted-delivery-molecular-repair/`、`domains/c3-generation-engine/ai-drug-discovery-protein-design/`、`domains/c6-local-unlocking/epigenetic-editing-gene-regulation-therapeutics/`、`domains/c1-boundary-rewriting/brain-preservation-connectomics-emulation/`、`domains/c4-conversion-channel/post-quantum-cryptography-long-term-data-security/`、`domains/c4-conversion-channel/safety-critical-software-formal-methods/` 和 `domains/c5-ecological-substrate/long-term-digital-preservation-format-migration/`：第三十三波正式研究域，分别承载纳米医学靶向递送、AI 药物发现蛋白设计、表观遗传编辑、脑保存连接组仿真、后量子密码长期数据安全、安全关键软件形式化方法和长期数字保存格式迁移。
- `domains/c2-source-maintenance/cerebrovascular-stroke-brain-perfusion-resilience/`、`domains/c2-source-maintenance/traumatic-brain-injury-neurotrauma-recovery/`、`domains/c2-source-maintenance/delirium-acute-cognitive-failure-prevention/`、`domains/c2-source-maintenance/disorders-of-consciousness-coma-recovery/`、`domains/c2-source-maintenance/epilepsy-seizure-network-stability/`、`domains/c2-source-maintenance/autonomic-nervous-system-homeostasis/` 和 `domains/c6-local-unlocking/migraine-headache-effective-time-burden/`：第三十四波正式研究域，分别承载卒中脑灌注韧性、TBI 神经创伤恢复、谵妄急性认知失败预防、意识障碍昏迷恢复、癫痫发作网络稳定、自主神经稳态和偏头痛有效时间负担。
- `domains/c2-source-maintenance/vision-eye-health-continuity/`、`domains/c2-source-maintenance/hearing-auditory-communication-continuity/`、`domains/c2-source-maintenance/vestibular-balance-spatial-orientation/`、`domains/c2-source-maintenance/speech-language-communication-continuity/`、`domains/c2-source-maintenance/swallowing-dysphagia-aspiration-nutrition/`、`domains/c2-source-maintenance/smell-taste-chemosensory-continuity/` 和 `domains/c2-source-maintenance/peripheral-neuropathy-somatosensory-continuity/`：第三十五波正式研究域，分别承载视觉眼健康、听力听觉沟通、前庭平衡空间定向、言语语言沟通、吞咽误吸营养、嗅味觉化学感知和周围神经躯体感觉连续性。
- `domains/c2-source-maintenance/cataract-vision-restoration-continuity/`、`domains/c6-local-unlocking/glaucoma-visual-field-protection-continuity/`、`domains/c2-source-maintenance/diabetic-retinopathy-screening-treatment-continuity/`、`domains/c2-source-maintenance/age-related-macular-degeneration-central-vision-continuity/`、`domains/c6-local-unlocking/refractive-error-glasses-contact-lens-continuity/`、`domains/c2-source-maintenance/low-vision-rehabilitation-assistive-technology-continuity/`、`domains/c2-source-maintenance/dry-eye-ocular-surface-comfort-continuity/`、`domains/c2-source-maintenance/eye-injury-urgent-vision-protection-continuity/`、`domains/c2-source-maintenance/pediatric-vision-screening-amblyopia-continuity/` 和 `domains/c6-local-unlocking/retinal-detachment-urgent-referral-continuity/`：第八十九波正式研究域，分别承载白内障视觉恢复、青光眼视野保护、糖尿病视网膜病变筛治、AMD 中央视觉、屈光矫正、低视力康复、干眼眼表舒适、眼外伤急性保护、儿童视筛弱视和视网膜脱离急转连续性。
- `domains/c2-source-maintenance/age-related-hearing-loss-hearing-aid-continuity/`、`domains/c2-source-maintenance/noise-induced-hearing-loss-prevention-continuity/`、`domains/c6-local-unlocking/tinnitus-sound-tolerance-sleep-continuity/`、`domains/c2-source-maintenance/otitis-media-child-hearing-development-continuity/`、`domains/c2-source-maintenance/sudden-hearing-loss-urgent-referral-continuity/`、`domains/c3-generation-engine/cochlear-implant-communication-continuity/`、`domains/c2-source-maintenance/newborn-hearing-screening-language-development-continuity/`、`domains/c2-source-maintenance/auditory-processing-listening-effort-continuity/`、`domains/c2-source-maintenance/hearing-assistive-devices-alerting-access-continuity/` 和 `domains/c3-generation-engine/captions-relay-service-communication-access-continuity/`：第九十波正式研究域，分别承载老年听损助听、噪声听损预防、耳鸣与声音耐受、儿童中耳炎听觉发育、突发听损急转、人工耳蜗沟通、新生儿听筛、听觉处理与听力负荷、听觉辅助设备和字幕/中继沟通访问连续性。
- `domains/c6-local-unlocking/bppv-positional-vertigo-continuity/`、`domains/c6-local-unlocking/menieres-disease-episodic-vertigo-continuity/`、`domains/c2-source-maintenance/vestibular-neuritis-labyrinthitis-acute-vertigo-continuity/`、`domains/c6-local-unlocking/persistent-postural-perceptual-dizziness-continuity/`、`domains/c2-source-maintenance/vestibular-migraine-dizziness-sensory-load-continuity/`、`domains/c2-source-maintenance/bilateral-vestibular-hypofunction-gaze-gait-stability-continuity/`、`domains/c2-source-maintenance/vestibular-rehabilitation-balance-compensation-continuity/`、`domains/c4-conversion-channel/gait-balance-assessment-fall-screening-continuity/`、`domains/c5-ecological-substrate/motion-sickness-transport-virtual-environment-tolerance-continuity/` 和 `domains/c2-source-maintenance/vestibular-ototoxicity-medication-chemical-risk-continuity/`：第九十一波正式研究域，分别承载位置性眩晕、梅尼埃病发作、急性前庭炎/迷路炎、PPPD 慢性头晕、前庭性偏头痛、双侧前庭低下、前庭康复补偿、步态平衡筛查、运动病/虚拟环境耐受和耳毒性前庭风险连续性。
- `domains/c3-generation-engine/aphasia-language-access-recovery-continuity/`、`domains/c2-source-maintenance/dysarthria-speech-intelligibility-continuity/`、`domains/c2-source-maintenance/apraxia-of-speech-motor-planning-continuity/`、`domains/c3-generation-engine/voice-disorders-phonation-communication-continuity/`、`domains/c6-local-unlocking/stuttering-fluency-participation-continuity/`、`domains/c3-generation-engine/developmental-language-disorder-child-communication-continuity/`、`domains/c2-source-maintenance/speech-sound-disorder-articulation-phonology-continuity/`、`domains/c3-generation-engine/augmentative-alternative-communication-aac-continuity/`、`domains/c3-generation-engine/social-communication-pragmatic-language-continuity/` 和 `domains/c3-generation-engine/cognitive-communication-disorder-executive-language-continuity/`：第九十二波正式研究域，分别承载失语、构音障碍、言语失用、嗓音障碍、口吃流畅性、发展性语言障碍、语音障碍、AAC、社会语用沟通和认知沟通执行连续性。
- `domains/c2-source-maintenance/oropharyngeal-dysphagia-swallow-safety-continuity/`、`domains/c6-local-unlocking/esophageal-dysphagia-motility-obstruction-continuity/`、`domains/c2-source-maintenance/aspiration-pneumonia-airway-protection-continuity/`、`domains/c2-source-maintenance/choking-foreign-body-airway-risk-continuity/`、`domains/c6-local-unlocking/texture-modified-diet-thickened-liquid-continuity/`、`domains/c6-local-unlocking/enteral-feeding-tube-nutrition-continuity/`、`domains/c2-source-maintenance/pediatric-feeding-swallowing-development-continuity/`、`domains/c2-source-maintenance/post-stroke-dysphagia-screening-recovery-continuity/`、`domains/c2-source-maintenance/neurodegenerative-dysphagia-nutrition-continuity/` 和 `domains/c6-local-unlocking/feeding-assistance-mealtime-dignity-continuity/`：第九十三波正式研究域，分别承载口咽吞咽、食管吞咽、误吸肺炎、窒息、质地调整饮食/稠液、管饲、儿童摄食吞咽、卒中后吞咽、神经退行性吞咽和进食协助用餐尊严连续性。
- `domains/c2-source-maintenance/urinary-tract-infection-pyelonephritis-urosepsis-continuity/`、`domains/c2-source-maintenance/catheter-associated-uti-device-infection-continuity/`、`domains/c6-local-unlocking/urinary-retention-bladder-emptying-continuity/`、`domains/c6-local-unlocking/overactive-bladder-nocturia-sleep-continuity/`、`domains/c2-source-maintenance/kidney-stone-obstruction-renal-colic-continuity/`、`domains/c6-local-unlocking/benign-prostatic-hyperplasia-luts-continuity/`、`domains/c6-local-unlocking/urinary-diversion-urostomy-supplies-continuity/`、`domains/c2-source-maintenance/dialysis-access-vascular-peritoneal-continuity/`、`domains/c2-source-maintenance/home-dialysis-supply-self-management-continuity/` 和 `domains/c2-source-maintenance/kidney-transplant-immunosuppression-graft-continuity/`：第九十四波正式研究域，分别承载尿路感染/肾盂肾炎/尿源性脓毒症、导尿相关 UTI、尿潴留、膀胱过度活动/夜尿、肾结石梗阻、BPH/LUTS、尿流改道/尿路造口、透析通路、家庭透析供应和肾移植免疫抑制连续性。
- `domains/c6-local-unlocking/pressure-injury-prevention-repositioning-support-surface-continuity/`、`domains/c2-source-maintenance/chronic-wound-venous-diabetic-pressure-ulcer-continuity/`、`domains/c2-source-maintenance/wound-infection-cellulitis-sepsis-continuity/`、`domains/c2-source-maintenance/diabetic-foot-ulcer-amputation-prevention-continuity/`、`domains/c2-source-maintenance/burn-wound-aftercare-scar-function-continuity/`、`domains/c2-source-maintenance/surgical-wound-dehiscence-ssi-continuity/`、`domains/c2-source-maintenance/incontinence-associated-dermatitis-moisture-skin-continuity/`、`domains/c6-local-unlocking/eczema-atopic-dermatitis-itch-sleep-continuity/`、`domains/c2-source-maintenance/psoriasis-inflammatory-skin-systemic-burden-continuity/` 和 `domains/c2-source-maintenance/skin-care-supplies-dressings-barrier-products-continuity/`：第九十五波正式研究域，分别承载压力损伤预防、慢性伤口、伤口感染/蜂窝织炎、糖尿病足、烧伤后创面、手术切口/SSI、潮湿相关皮炎、湿疹瘙痒睡眠、银屑病系统负担和皮肤护理用品连续性。
- `domains/c6-local-unlocking/bathroom-bathing-toileting-transfer-fall-safety-continuity/`、`domains/c6-local-unlocking/stairs-steps-handrail-threshold-fall-safety-continuity/`、`domains/c5-ecological-substrate/home-lighting-nighttime-pathway-visibility-continuity/`、`domains/c6-local-unlocking/bedroom-bed-transfer-entrapment-safety-continuity/`、`domains/c5-ecological-substrate/smoke-alarm-home-fire-escape-readiness-continuity/`、`domains/c6-local-unlocking/carbon-monoxide-alarm-combustion-appliance-safety-continuity/`、`domains/c6-local-unlocking/furniture-tv-tip-over-anchoring-child-safety-continuity/`、`domains/c5-ecological-substrate/household-poison-storage-child-resistant-packaging-continuity/`、`domains/c6-local-unlocking/window-covering-cord-strangulation-child-safety-continuity/` 和 `domains/c2-source-maintenance/hot-water-scald-burn-prevention-continuity/`：第九十六波正式研究域，分别承载浴室洗澡如厕转移、楼梯台阶扶手门槛、夜间路径照明、卧室床转移夹陷、烟雾报警家庭逃生、一氧化碳报警燃烧设备、家具/电视倾倒锚固、家庭毒物储存儿童防护包装、窗饰拉绳勒颈和热水烫伤预防连续性。
- `domains/c5-ecological-substrate/drowning-water-safety-supervision-continuity/`、`domains/c6-local-unlocking/pool-spa-barrier-drain-entrapment-safety-continuity/`、`domains/c5-ecological-substrate/boating-life-jacket-watercraft-safety-continuity/`、`domains/c6-local-unlocking/child-passenger-safety-car-seat-restraint-continuity/`、`domains/c6-local-unlocking/bicycle-helmet-wheeled-sports-head-injury-prevention-continuity/`、`domains/c6-local-unlocking/playground-surface-equipment-fall-injury-prevention-continuity/`、`domains/c4-conversion-channel/sports-concussion-return-to-play-protocol-continuity/`、`domains/c6-local-unlocking/infant-safe-sleep-suid-risk-reduction-continuity/`、`domains/c6-local-unlocking/firearm-safe-storage-injury-prevention-continuity/` 和 `domains/c6-local-unlocking/atv-off-highway-vehicle-injury-prevention-continuity/`：第九十七波正式研究域，分别承载溺水水域安全、泳池/水疗池屏障与排水夹陷、船艇救生衣、儿童乘员约束、轮式运动头部伤害、游乐场表面设备、运动脑震荡返学返赛、婴儿安全睡眠、枪支安全储存和 ATV/OHV 伤害预防连续性。
- `domains/c5-ecological-substrate/emergency-supply-kit-go-bag-rotation-continuity/`、`domains/c3-generation-engine/family-emergency-communication-reunification-continuity/`、`domains/c5-ecological-substrate/evacuation-route-transportation-shelter-plan-continuity/`、`domains/c3-generation-engine/shelter-in-place-clean-air-room-indoor-protection-continuity/`、`domains/c6-local-unlocking/backup-power-battery-generator-safety-continuity/`、`domains/c5-ecological-substrate/emergency-food-water-storage-treatment-continuity/`、`domains/c6-local-unlocking/refrigerated-medication-medical-device-power-outage-continuity/`、`domains/c5-ecological-substrate/emergency-financial-document-cash-readiness-continuity/`、`domains/c3-generation-engine/disability-access-functional-needs-personal-preparedness-continuity/` 和 `domains/c5-ecological-substrate/older-adult-caregiver-disaster-preparedness-continuity/`：第九十八波正式研究域，分别承载应急物资包、家庭应急通信团聚、撤离交通避难、就地避险清洁空气房、备用电与发电机安全、应急食水、温控药品/医疗设备停电、应急金融文件现金、残障功能需求个人准备和老年照护者灾害准备连续性。
- `domains/c4-conversion-channel/disaster-individual-assistance-benefits-navigation-continuity/`、`domains/c5-ecological-substrate/disaster-temporary-housing-displacement-recovery-continuity/`、`domains/c5-ecological-substrate/disaster-recovery-center-service-access-continuity/`、`domains/c5-ecological-substrate/disaster-case-management-long-term-recovery-continuity/`、`domains/c5-ecological-substrate/disaster-unemployment-income-disruption-continuity/`、`domains/c3-generation-engine/disaster-legal-aid-rights-claims-continuity/`、`domains/c5-ecological-substrate/disaster-debris-waste-sanitation-cleanup-continuity/`、`domains/c5-ecological-substrate/post-flood-mold-moisture-indoor-recovery-continuity/`、`domains/c5-ecological-substrate/disaster-behavioral-health-distress-recovery-continuity/` 和 `domains/c5-ecological-substrate/disaster-volunteer-donations-management-continuity/`：第九十九波正式研究域，分别承载灾后个人援助导航、临时住房与流离恢复、恢复中心服务可达、长期个案管理、灾害失业收入中断、灾害法律援助、灾后废弃物卫生清理、洪水后霉菌湿气室内恢复、灾害行为健康恢复和灾害志愿捐赠管理连续性。
- `domains/c5-ecological-substrate/space-weather-geomagnetic-storm-resilience/`、`domains/c6-local-unlocking/planetary-defense-near-earth-object-risk/`、`domains/c5-ecological-substrate/volcanic-ashfall-geohazard-continuity/`、`domains/c5-ecological-substrate/earthquake-seismic-risk-built-environment-continuity/`、`domains/c5-ecological-substrate/tsunami-warning-coastal-evacuation-continuity/` 和 `domains/c4-conversion-channel/extreme-heat-cooling-public-health-continuity/`：第三十六波正式研究域，分别承载空间天气地磁暴、行星防御近地天体、火山灰地质灾害、地震建成环境、海啸预警沿海撤离和极端高温制冷公共卫生连续性。
- `domains/c6-local-unlocking/noise-exposure-acoustic-environment-continuity/`、`domains/c6-local-unlocking/light-exposure-circadian-environment-continuity/`、`domains/c4-conversion-channel/lead-heavy-metal-exposure-control/`、`domains/c6-local-unlocking/radon-asbestos-indoor-hazard-continuity/`、`domains/c2-source-maintenance/mold-dampness-indoor-biological-exposure/` 和 `domains/c6-local-unlocking/vector-borne-disease-environmental-control/`：第三十七波正式研究域，分别承载噪声声环境、光照昼夜节律、铅与重金属暴露、氡与石棉室内危害、霉菌潮湿室内生物暴露和病媒传播环境控制。
- `domains/c6-local-unlocking/advance-care-planning-medical-decision-continuity/`、`domains/c6-local-unlocking/supported-decision-making-guardianship-rights/`、`domains/c3-generation-engine/healthcare-personal-representative-hipaa-access-continuity/`、`domains/c5-ecological-substrate/financial-fiduciary-power-of-attorney-continuity/`、`domains/c4-conversion-channel/representative-payee-benefits-management-continuity/` 和 `domains/c6-local-unlocking/trust-estate-affairs-succession-continuity/`：第三十八波正式研究域，分别承载预先医疗照护计划、支持性决策监护权利、医疗个人代表 HIPAA 访问、财务受托授权代理、代表收款人福利代管和事务信托遗产继承连续性。
- `domains/c6-local-unlocking/credit-consumer-reporting-access-continuity/`、`domains/c4-conversion-channel/tenant-screening-rental-access-continuity/`、`domains/c4-conversion-channel/background-check-record-screening-continuity/`、`domains/c4-conversion-channel/employment-algorithmic-hiring-screening-continuity/`、`domains/c5-ecological-substrate/insurance-underwriting-algorithmic-risk-scoring-continuity/` 和 `domains/c4-conversion-channel/public-benefits-eligibility-automated-decision-continuity/`：第三十九波正式研究域，分别承载信用与消费者报告、租房筛查、背景记录筛查、算法招聘、保险算法评分和公共福利自动资格系统。
- `domains/c3-generation-engine/education-record-transcript-verification-continuity/`、`domains/c4-conversion-channel/professional-licensure-certification-continuity/`、`domains/c3-generation-engine/skills-competency-credentialing-continuity/`、`domains/c3-generation-engine/continuing-education-recertification-continuity/`、`domains/c3-generation-engine/apprenticeship-work-based-learning-continuity/` 和 `domains/c3-generation-engine/verifiable-credential-wallet-interoperability/`：第四十波正式研究域，分别承载教育记录核验、职业证照认证、技能胜任力凭证、继续教育再认证、学徒制工作中学习和可验证凭证钱包互操作。
- `domains/c6-local-unlocking/income-payroll-employment-record-continuity/`、`domains/c6-local-unlocking/tax-administration-filing-record-continuity/`、`domains/c4-conversion-channel/social-security-earnings-benefit-record-continuity/`、`domains/c6-local-unlocking/retirement-pension-savings-plan-continuity/`、`domains/c5-ecological-substrate/unemployment-insurance-wage-record-continuity/` 和 `domains/c4-conversion-channel/workers-compensation-occupational-injury-benefit-continuity/`：第四十一波正式研究域，分别承载工资雇佣记录、税务申报记录、社会保险收入与福利记录、退休养老金计划、失业保险工资记录和工伤职业伤害权益。
- `domains/c6-local-unlocking/family-medical-leave-job-protection-continuity/`、`domains/c6-local-unlocking/paid-sick-family-leave-wage-replacement-continuity/`、`domains/c2-source-maintenance/pregnancy-parental-work-continuity/`、`domains/c5-ecological-substrate/workplace-accommodation-return-to-work-continuity/`、`domains/c4-conversion-channel/disability-income-work-capacity-benefit-continuity/` 和 `domains/c6-local-unlocking/family-caregiver-respite-work-continuity/`：第四十二波正式研究域，分别承载家庭医疗假岗位保护、带薪病假/家庭假工资替代、孕产育儿工作连续性、合理便利复工、残障收入与工作能力福利、家庭照护者喘息与工作连续性。
- `domains/c5-ecological-substrate/adult-day-services-supervision-transport-continuity/`、`domains/c3-generation-engine/home-care-aide-personal-care-workforce-continuity/`、`domains/c6-local-unlocking/respite-care-provider-capacity-scheduling-continuity/`、`domains/c3-generation-engine/caregiver-training-skills-safety-continuity/`、`domains/c2-source-maintenance/caregiver-health-burnout-screening-support-continuity/` 和 `domains/c5-ecological-substrate/home-care-task-coordination-care-plan-continuity/`：第一百一十五波正式研究域，分别承载成人日间服务监督交通、居家照护人员与个人照护劳动力、喘息服务供给容量排班、照护者训练技能安全、照护者健康倦怠筛查支持和居家照护任务协调 care plan 连续性。
- `domains/c6-local-unlocking/tribal-health-sovereignty-service-access-continuity/`、`domains/c4-conversion-channel/veterans-health-benefits-navigation-continuity/`、`domains/c5-ecological-substrate/migrant-seasonal-farmworker-health-housing-continuity/`、`domains/c5-ecological-substrate/territorial-island-health-infrastructure-access-continuity/`、`domains/c5-ecological-substrate/border-community-cross-border-care-continuity/` 和 `domains/c4-conversion-channel/lgbtq-health-identity-affirming-service-continuity/`：第一百一十六波正式研究域，分别承载部落健康主权服务、退伍军人健康福利导航、迁徙季节性农业工人健康住房、属地岛屿健康基础设施、边境跨境照护和 LGBTQ 身份承认肯定性服务连续性。
- `domains/c5-ecological-substrate/runaway-homeless-youth-outreach-shelter-continuity/`、`domains/c6-local-unlocking/foster-care-aging-out-independent-living-continuity/`、`domains/c5-ecological-substrate/juvenile-justice-reentry-aftercare-continuity/`、`domains/c5-ecological-substrate/transition-age-youth-mental-health-service-continuity/`、`domains/c3-generation-engine/opportunity-youth-education-employment-pathway-continuity/` 和 `domains/c6-local-unlocking/pregnant-parenting-youth-family-support-continuity/`：第一百一十七波正式研究域，分别承载离家无家可归青年外展庇护、寄养出离独立生活、少年司法重返 aftercare、过渡年龄青年心理健康服务、机会青年教育就业路径和怀孕育儿青年家庭支持连续性。
- `domains/c4-conversion-channel/prenatal-care-access-risk-screening-continuity/`、`domains/c6-local-unlocking/postpartum-care-recovery-follow-up-continuity/`、`domains/c2-source-maintenance/lactation-breastfeeding-support-continuity/`、`domains/c5-ecological-substrate/preterm-birth-nicu-discharge-transition-continuity/`、`domains/c2-source-maintenance/pregnancy-loss-stillbirth-bereavement-continuity/` 和 `domains/c4-conversion-channel/perinatal-mental-health-screening-referral-continuity/`：第一百一十八波正式研究域，分别承载产前照护接入风险筛查、产后恢复随访、哺乳泵奶支持、早产 NICU 出院转接、妊娠丧失死产悲伤支持和围产期心理健康筛查转介连续性。
- `domains/c2-source-maintenance/newborn-screening-result-followup-continuity/`、`domains/c6-local-unlocking/well-child-visit-preventive-care-continuity/`、`domains/c2-source-maintenance/childhood-immunization-schedule-record-continuity/`、`domains/c4-conversion-channel/developmental-behavioral-screening-referral-continuity/`、`domains/c2-source-maintenance/pediatric-lead-screening-environmental-followup-continuity/` 和 `domains/c6-local-unlocking/children-youth-special-health-care-needs-care-coordination-continuity/`：第一百一十九波正式研究域，分别承载新生儿筛查结果随访、儿童健康体检预防照护、儿童免疫排程记录、发育行为筛查转介、儿童铅筛查环境随访和特殊健康需求儿童照护协调连续性。
- `domains/c5-ecological-substrate/summer-ebt-sun-bucks-school-break-food-continuity/`、`domains/c5-ecological-substrate/summer-food-service-program-site-access-continuity/`、`domains/c5-ecological-substrate/cacfp-child-adult-care-food-program-continuity/`、`domains/c6-local-unlocking/afterschool-snack-supper-meal-continuity/`、`domains/c5-ecological-substrate/special-diet-allergy-school-meal-accommodation-continuity/` 和 `domains/c5-ecological-substrate/school-meal-debt-unpaid-balance-stigma-continuity/`：第一百二十二波正式研究域，分别承载 Summer EBT / SUN Bucks、SFSP 暑期供餐站点、CACFP、课后点心晚餐、特殊饮食/过敏校餐便利和校餐欠费污名这些儿童营养项目执行连续性。
- `domains/c4-conversion-channel/nutrition-insecurity-screening-referral-continuity/`、`domains/c6-local-unlocking/medically-tailored-meals-chronic-care-continuity/`、`domains/c4-conversion-channel/medically-tailored-groceries-food-benefit-continuity/`、`domains/c4-conversion-channel/produce-prescription-fruit-vegetable-benefit-continuity/`、`domains/c5-ecological-substrate/food-pharmacy-clinic-pantry-integration-continuity/` 和 `domains/c6-local-unlocking/medical-nutrition-therapy-dietitian-access-continuity/`：第一百二十三波正式研究域，分别承载 Food is Medicine / 医疗营养支持执行连续性中的营养不安全筛查转介、医学定制餐、医学定制食材、蔬果处方、临床 food pharmacy/pantry 和医学营养治疗营养师可达。
- `domains/c2-source-maintenance/assisted-reproductive-technology-ivf-cycle-continuity/`、`domains/c4-conversion-channel/art-clinic-success-rate-quality-reporting-continuity/`、`domains/c2-source-maintenance/fertility-preservation-gamete-embryo-cryostorage-continuity/`、`domains/c2-source-maintenance/reproductive-tissue-donor-screening-traceability-continuity/`、`domains/c6-local-unlocking/preimplantation-genetic-testing-embryo-selection-governance-continuity/` 和 `domains/c5-ecological-substrate/third-party-reproduction-surrogacy-donor-legal-ethics-continuity/`：第一百二十四波正式研究域，分别承载 ART/IVF 周期、ART 诊所成功率质量报告、生育保存冷冻储存、生殖组织供体筛查追溯、PGT 胚胎选择治理和第三方生殖法律伦理。
- `domains/c4-conversion-channel/vital-records-life-event-continuity/`、`domains/c4-conversion-channel/name-change-identity-record-synchronization-continuity/`、`domains/c6-local-unlocking/address-residency-mail-service-continuity/`、`domains/c4-conversion-channel/household-composition-dependent-eligibility-continuity/`、`domains/c6-local-unlocking/family-law-custody-child-support-continuity/` 和 `domains/c6-local-unlocking/kinship-foster-adoption-care-continuity/`：第四十三波正式研究域，分别承载生命事件记录、姓名变更同步、地址居住地邮件路由、家庭组成资格关系、家庭法监护抚养、亲属照护寄养收养。
- `domains/c5-ecological-substrate/banking-deposit-account-access-continuity/`、`domains/c6-local-unlocking/debt-obligation-collection-relief-continuity/`、`domains/c6-local-unlocking/real-property-title-deed-record-continuity/`、`domains/c6-local-unlocking/driver-license-vehicle-registration-continuity/`、`domains/c6-local-unlocking/passport-travel-document-mobility-continuity/`、`domains/c6-local-unlocking/contract-subscription-billing-consent-continuity/` 和 `domains/c6-local-unlocking/notary-document-authentication-signature-continuity/`：第四十四波正式研究域，分别承载银行账户存款访问、债务义务催收救济、不动产权属地契、驾照车辆登记、护照旅行证件、合同订阅账单、公证文件认证签名连续性。
- `domains/c6-local-unlocking/citizenship-nationality-statelessness-continuity/`、`domains/c6-local-unlocking/immigration-status-residency-work-authorization-continuity/`、`domains/c5-ecological-substrate/asylum-refugee-protection-status-continuity/`、`domains/c6-local-unlocking/detention-custody-confinement-status-continuity/`、`domains/c6-local-unlocking/civil-commitment-involuntary-treatment-rights-continuity/`、`domains/c5-ecological-substrate/court-notice-service-process-default-judgment-continuity/` 和 `domains/c6-local-unlocking/criminal-record-relief-collateral-consequences-continuity/`：第四十五波正式研究域，分别承载公民国籍无国籍、移民居留工作授权、庇护难民保护、拘押羁押监管状态、非自愿治疗权利、法院通知缺席判决和犯罪记录附带后果连续性。
- `domains/c5-ecological-substrate/school-enrollment-attendance-continuity/`、`domains/c3-generation-engine/special-education-iep-504-accommodation-continuity/`、`domains/c5-ecological-substrate/school-meals-nutrition-access-continuity/`、`domains/c5-ecological-substrate/school-health-services-chronic-condition-continuity/`、`domains/c5-ecological-substrate/school-transportation-safe-routes-continuity/`、`domains/c5-ecological-substrate/school-discipline-exclusion-restraint-continuity/`、`domains/c5-ecological-substrate/school-mental-health-counseling-support-continuity/` 和 `domains/c5-ecological-substrate/school-climate-bullying-violence-prevention-continuity/`：第四十六波正式研究域，分别承载入学出勤、特殊教育 IEP/504、校餐营养、学校健康服务、通学安全、纪律排除约束、学校心理健康和学校气候欺凌暴力预防连续性。
- `domains/c6-local-unlocking/postsecondary-admissions-transfer-articulation-continuity/`、`domains/c3-generation-engine/student-financial-aid-grant-scholarship-continuity/`、`domains/c6-local-unlocking/academic-advising-degree-progress-continuity/`、`domains/c6-local-unlocking/campus-basic-needs-student-support-continuity/`、`domains/c6-local-unlocking/campus-disability-accommodations-accessibility-continuity/`、`domains/c6-local-unlocking/campus-mental-health-crisis-student-support-continuity/`、`domains/c6-local-unlocking/campus-safety-title-ix-clery-continuity/` 和 `domains/c6-local-unlocking/international-student-sevis-status-continuity/`：第四十七波正式研究域，分别承载高等教育入学转学衔接、学生资助奖助学金、学业指导学位进度、校园基本需求、校园残障便利、校园心理危机支持、校园安全 Title IX/Clery 和国际学生 SEVIS 身份连续性。
- `domains/c6-local-unlocking/email-account-recovery-continuity/`、`domains/c6-local-unlocking/phone-number-sim-portability-account-security-continuity/`、`domains/c3-generation-engine/mfa-passkey-credential-recovery-continuity/`、`domains/c6-local-unlocking/password-manager-secret-vault-continuity/`、`domains/c4-conversion-channel/cloud-backup-file-sync-data-portability-continuity/`、`domains/c6-local-unlocking/messaging-contact-graph-portability-continuity/`、`domains/c6-local-unlocking/domain-dns-web-presence-continuity/` 和 `domains/c6-local-unlocking/platform-account-suspension-appeals-continuity/`：第四十八波正式研究域，分别承载邮箱账号恢复、手机号/SIM/携转安全、MFA/passkey 凭证恢复、密码管理器密钥库、云备份文件同步数据可携带、消息联系人图谱可携带、域名 DNS Web 存在和平台账号停权申诉连续性。
- `domains/c3-generation-engine/personal-computing-device-lifecycle-repair-continuity/`、`domains/c5-ecological-substrate/home-network-router-iot-security-continuity/`、`domains/c4-conversion-channel/software-supply-chain-dependency-provenance-continuity/`、`domains/c4-conversion-channel/software-update-vulnerability-patch-continuity/`、`domains/c6-local-unlocking/open-source-maintainer-sustainability-continuity/`、`domains/c6-local-unlocking/pki-certificate-cryptographic-trust-continuity/`、`domains/c4-conversion-channel/cloud-service-exit-interoperability-continuity/` 和 `domains/c6-local-unlocking/api-platform-dependency-runtime-continuity/`：第四十九波正式研究域，分别承载个人计算设备生命周期维修、家庭网络路由器 IoT 安全、软件供应链依赖来源证明、软件更新漏洞补丁、开源维护者可持续、PKI 证书密码信任、云服务退出互操作和 API 平台运行时依赖连续性。
- `domains/c6-local-unlocking/calendar-scheduling-appointment-continuity/`、`domains/c3-generation-engine/notification-alert-routing-attention-continuity/`、`domains/c6-local-unlocking/reminder-alarm-routine-task-continuity/`、`domains/c6-local-unlocking/meeting-video-conferencing-remote-collaboration-continuity/`、`domains/c6-local-unlocking/document-capture-ocr-pdf-record-workflow-continuity/`、`domains/c6-local-unlocking/search-index-discovery-retrieval-continuity/`、`domains/c3-generation-engine/personal-automation-integration-workflow-continuity/` 和 `domains/c6-local-unlocking/collaborative-document-permission-version-continuity/`：第五十波正式研究域，分别承载日历排程预约、通知警报路由、提醒闹钟例行任务、会议视频远程协作、文件捕获 OCR PDF 记录流、搜索索引发现检索、个人自动化集成工作流和协作文档权限版本连续性。
- `domains/c5-ecological-substrate/home-access-lock-key-entry-continuity/`、`domains/c5-ecological-substrate/household-appliance-maintenance-repair-continuity/`、`domains/c5-ecological-substrate/home-refrigeration-food-storage-continuity/`、`domains/c6-local-unlocking/cooking-meal-preparation-kitchen-safety-continuity/`、`domains/c6-local-unlocking/laundry-clothing-footwear-hygiene-continuity/`、`domains/c5-ecological-substrate/household-cleaning-disinfection-pest-control-continuity/`、`domains/c6-local-unlocking/postal-parcel-delivery-pickup-continuity/` 和 `domains/c5-ecological-substrate/household-maintenance-repair-contractor-continuity/`：第五十一波正式研究域，分别承载住所进入、家电维护、家庭冷藏、烹饪备餐、衣物鞋履卫生、家庭清洁消毒害虫控制、邮件包裹接收和家庭维修承包商连续性。
- `domains/c3-generation-engine/personal-vehicle-maintenance-recall-repair-continuity/`、`domains/c5-ecological-substrate/fuel-ev-charging-refueling-access-continuity/`、`domains/c6-local-unlocking/parking-curb-access-towing-impound-continuity/`、`domains/c6-local-unlocking/walking-bicycling-micromobility-continuity/`、`domains/c6-local-unlocking/paratransit-nemt-access-continuity/`、`domains/c6-local-unlocking/taxi-rideshare-demand-response-mobility-continuity/`、`domains/c5-ecological-substrate/transit-fare-payment-toll-account-continuity/` 和 `domains/c6-local-unlocking/multimodal-trip-planning-real-time-wayfinding-continuity/`：第五十二波正式研究域，分别承载个人车辆维护召回维修、燃料/EV 充电补能、停车路缘拖车扣押、步行骑行微移动、paratransit/NEMT、出租车网约车需求响应交通、交通票卡/过路费账户和多模式实时导向连续性。
- `domains/c4-conversion-channel/public-restroom-sanitation-hygiene-access-continuity/`、`domains/c4-conversion-channel/public-drinking-water-hydration-access-continuity/`、`domains/c4-conversion-channel/public-seating-shade-rest-cooling-access-continuity/`、`domains/c5-ecological-substrate/community-resilience-hub-shelter-center-continuity/`、`domains/c4-conversion-channel/public-library-community-anchor-access-continuity/`、`domains/c6-local-unlocking/parks-recreation-green-space-access-continuity/`、`domains/c4-conversion-channel/public-wifi-device-charging-connectivity-continuity/` 和 `domains/c4-conversion-channel/public-accommodation-accessibility-service-continuity/`：第五十三波正式研究域，分别承载公共厕所卫生、公共饮水补水、公共座椅遮阴休息降温、社区韧性/避难中心、公共图书馆社区锚点、公园娱乐绿地、公共 Wi-Fi/设备充电和公共场所无障碍服务连续性。
- `domains/c5-ecological-substrate/grocery-retail-food-store-access-continuity/`、`domains/c5-ecological-substrate/snap-ebt-redemption-retailer-payment-continuity/`、`domains/c2-source-maintenance/wic-benefit-redemption-infant-maternal-nutrition-continuity/`、`domains/c5-ecological-substrate/food-bank-pantry-community-food-distribution-continuity/`、`domains/c5-ecological-substrate/emergency-food-disaster-feeding-continuity/`、`domains/c5-ecological-substrate/home-delivered-meals-congregate-nutrition-services-continuity/`、`domains/c5-ecological-substrate/infant-formula-baby-food-supply-safety-continuity/` 和 `domains/c5-ecological-substrate/prepared-food-restaurant-cafeteria-safety-access-continuity/`：第五十四波正式研究域，分别承载 grocery/食品零售、SNAP EBT 兑换、WIC 母婴营养兑换、食品银行/pantry、灾害供餐、送餐/集体营养服务、婴儿配方/婴幼儿食品供应安全和餐馆/cafeteria 熟食安全可达连续性。
- `domains/c6-local-unlocking/retail-pharmacy-prescription-dispensing-continuity/`、`domains/c4-conversion-channel/pharmacy-benefit-formulary-prior-authorization-continuity/`、`domains/c6-local-unlocking/medication-reconciliation-regimen-adherence-continuity/`、`domains/c4-conversion-channel/patient-medication-labeling-counseling-continuity/`、`domains/c4-conversion-channel/unused-medicine-takeback-disposal-continuity/`、`domains/c6-local-unlocking/durable-medical-equipment-supplier-repair-continuity/`、`domains/c2-source-maintenance/home-oxygen-respiratory-equipment-supply-continuity/` 和 `domains/c2-source-maintenance/diabetes-insulin-glucose-monitoring-supplies-continuity/`：第五十五波正式研究域，分别承载药房处方配药、药品福利/处方集/事前授权、用药核对与依从执行、患者药品标签/咨询理解、未用药回收处置、DME 供应维修、居家氧疗/呼吸设备供应和糖尿病胰岛素/血糖监测耗材连续性。
- `domains/c6-local-unlocking/provider-directory-network-adequacy-continuity/`、`domains/c6-local-unlocking/primary-care-panel-appointment-access-continuity/`、`domains/c4-conversion-channel/specialist-referral-authorization-navigation-continuity/`、`domains/c6-local-unlocking/appointment-availability-wait-time-continuity/`、`domains/c6-local-unlocking/outpatient-laboratory-specimen-result-routing-continuity/`、`domains/c6-local-unlocking/diagnostic-imaging-order-scheduling-report-continuity/`、`domains/c6-local-unlocking/ambulatory-procedure-surgery-center-continuity/` 和 `domains/c6-local-unlocking/after-hours-urgent-care-triage-continuity/`：第五十六波正式研究域，分别承载 provider 名录/网络充足性、初级照护 panel/预约、专科转诊/授权导航、预约容量/等待时间、门诊检验标本/结果路由、诊断影像医嘱/报告回传、门诊操作/ASC 和非工作时间 urgent care/triage 连续性。
- `domains/c5-ecological-substrate/health-insurance-enrollment-renewal-continuity/`、`domains/c4-conversion-channel/insurance-eligibility-benefits-verification-continuity/`、`domains/c6-local-unlocking/medical-service-prior-authorization-utilization-management-continuity/`、`domains/c6-local-unlocking/claims-adjudication-eob-denial-continuity/`、`domains/c4-conversion-channel/patient-billing-payment-plan-continuity/`、`domains/c6-local-unlocking/price-transparency-good-faith-estimate-continuity/`、`domains/c6-local-unlocking/surprise-billing-balance-bill-protection-continuity/` 和 `domains/c5-ecological-substrate/charity-care-financial-assistance-medical-debt-continuity/`：第五十七波正式研究域，分别承载健康保险参保续保、权益核验、医疗服务授权、理赔/EOB/拒付、患者账单/付款计划、价格透明/GFE、意外账单保护和 charity care/医疗债务连续性。
- `domains/c4-conversion-channel/patient-portal-account-message-continuity/`、`domains/c6-local-unlocking/medical-record-access-amendment-release-continuity/`、`domains/c6-local-unlocking/clinical-results-notification-followup-continuity/`、`domains/c6-local-unlocking/informed-consent-refusal-shared-decision-continuity/`、`domains/c3-generation-engine/healthcare-language-interpreter-effective-communication-continuity/`、`domains/c4-conversion-channel/healthcare-disability-accommodation-accessibility-continuity/`、`domains/c4-conversion-channel/patient-grievance-complaint-ombuds-continuity/` 和 `domains/c4-conversion-channel/healthcare-civil-rights-nondiscrimination-continuity/`：第五十八波正式研究域，分别承载患者门户/医疗消息、病历访问修正释放、临床结果通知随访、知情同意/拒绝/共同决策、医疗语言服务、医疗残障便利、患者投诉/ombuds 和医疗民权反歧视连续性。
- `domains/c5-ecological-substrate/emergency-contact-next-of-kin-notification-continuity/`、`domains/c3-generation-engine/personal-health-record-emergency-summary-continuity/`、`domains/c5-ecological-substrate/medical-id-allergy-critical-alert-continuity/`、`domains/c5-ecological-substrate/medication-list-implant-device-emergency-continuity/`、`domains/c5-ecological-substrate/chronic-condition-emergency-action-plan-continuity/`、`domains/c2-source-maintenance/immunization-record-proof-continuity/`、`domains/c2-source-maintenance/organ-donor-registry-anatomical-gift-continuity/` 和 `domains/c4-conversion-channel/access-functional-needs-emergency-registry-continuity/`：第五十九波正式研究域，分别承载紧急联系人/近亲通知、个人健康记录急救摘要、医疗 ID/过敏关键警报、药物清单/植入设备急救转交、慢病急救行动计划、免疫记录证明、器官捐赠登记和 access/functional needs 急救登记连续性。
- `domains/c6-local-unlocking/death-certificate-registration-cause-of-death-record-continuity/`、`domains/c6-local-unlocking/funeral-cremation-burial-disposition-continuity/`、`domains/c6-local-unlocking/cemetery-memorial-remains-location-continuity/`、`domains/c6-local-unlocking/bereavement-leave-grief-support-continuity/`、`domains/c4-conversion-channel/survivor-benefits-death-notification-continuity/`、`domains/c5-ecological-substrate/life-insurance-beneficiary-claim-continuity/`、`domains/c6-local-unlocking/estate-inventory-asset-liability-handoff-continuity/` 和 `domains/c6-local-unlocking/post-death-account-closure-service-cancellation-continuity/`：第六十波正式研究域，分别承载死亡证明/死因记录、葬礼火化土葬与遗体处置、墓地纪念与遗体位置、丧亲假与悲伤支持、遗属福利死亡通知、寿险受益人理赔、遗产清单资产负债交接和死亡后账户关闭服务取消连续性。
- `domains/c6-local-unlocking/loneliness-social-isolation-risk-continuity/`、`domains/c5-ecological-substrate/social-prescribing-community-referral-continuity/`、`domains/c3-generation-engine/mutual-aid-neighbor-support-network-continuity/`、`domains/c5-ecological-substrate/volunteering-civic-service-participation-continuity/`、`domains/c5-ecological-substrate/community-mediation-neighbor-conflict-resolution-continuity/`、`domains/c5-ecological-substrate/restorative-justice-repair-accountability-continuity/`、`domains/c4-conversion-channel/reputation-defamation-public-trust-repair-continuity/`、`domains/c6-local-unlocking/references-vouching-recommendation-social-capital-continuity/` 和 `domains/c6-local-unlocking/third-place-belonging-social-participation-continuity/`：第六十一波正式研究域，分别承载孤独/社会隔离风险、社会处方/社区转介、互助邻里支持、志愿服务/公民参与、社区调解/邻里冲突、修复性司法/责任修复、声誉诽谤/公共信任修复、推荐背书/社会资本和第三空间/归属参与连续性。
- `domains/c6-local-unlocking/purpose-meaning-existential-continuity/`、`domains/c6-local-unlocking/spiritual-care-religious-practice-continuity/`、`domains/c4-conversion-channel/cultural-heritage-identity-continuity/`、`domains/c6-local-unlocking/arts-creative-expression-participation-continuity/`、`domains/c6-local-unlocking/leisure-recreation-restorative-activity-continuity/`、`domains/c4-conversion-channel/narrative-identity-life-review-continuity/`、`domains/c5-ecological-substrate/ritual-ceremony-life-transition-continuity/` 和 `domains/c6-local-unlocking/dignity-personhood-respect-continuity/`：第六十二波正式研究域，分别承载目的意义/存在连续性、精神照护/宗教实践、文化遗产/身份、艺术创造表达、休闲娱乐恢复、叙事身份/生命回顾、仪式典礼/生命过渡和尊严人格承认连续性。
- `domains/c6-local-unlocking/human-factors-ergonomics-task-system-continuity/`、`domains/c3-generation-engine/cognitive-load-workload-measurement-continuity/`、`domains/c6-local-unlocking/fatigue-risk-alertness-continuity/`、`domains/c6-local-unlocking/situational-awareness-decision-environment-continuity/`、`domains/c6-local-unlocking/handoff-checklist-procedure-reliability-continuity/`、`domains/c3-generation-engine/incident-reporting-just-culture-learning-continuity/`、`domains/c3-generation-engine/automation-bias-mode-confusion-oversight-continuity/` 和 `domains/c6-local-unlocking/alert-fatigue-interruption-signal-management-continuity/`：第六十三波正式研究域，分别承载人因/工效学任务系统、认知负荷/工作负荷测量、疲劳风险/警觉性、情境感知/决策环境、交接清单/过程可靠性、事件报告/公正文化学习、自动化偏误/模式混淆监督和告警疲劳/中断信号管理连续性。
- `domains/c6-local-unlocking/depression-mood-disorder-functioning-continuity/`、`domains/c6-local-unlocking/anxiety-stress-threat-regulation-continuity/`、`domains/c2-source-maintenance/trauma-ptsd-adversity-recovery-continuity/`、`domains/c5-ecological-substrate/psychosis-reality-testing-community-continuity/`、`domains/c6-local-unlocking/bipolar-mood-episode-stability-continuity/`、`domains/c2-source-maintenance/adhd-executive-function-neurodevelopment-continuity/`、`domains/c2-source-maintenance/autism-neurodiversity-support-continuity/` 和 `domains/c6-local-unlocking/eating-disorders-nutrition-body-continuity/`：第六十四波正式研究域，分别承载抑郁/心境功能、焦虑/压力威胁调节、创伤/PTSD 恢复、精神病性现实检验、双相情绪周期、ADHD 执行功能、自闭神经多样性支持和进食障碍营养身体连续性。
- `domains/c3-generation-engine/ai-evaluation-benchmark-validity-continuity/`、`domains/c3-generation-engine/ai-red-teaming-adversarial-testing-continuity/`、`domains/c3-generation-engine/ai-incident-reporting-post-deployment-monitoring-continuity/`、`domains/c3-generation-engine/ai-data-provenance-contamination-drift-continuity/`、`domains/c2-source-maintenance/synthetic-data-generation-validation-continuity/`、`domains/c3-generation-engine/ai-model-supply-chain-provenance-release-continuity/`、`domains/c3-generation-engine/ai-agent-tool-permission-sandbox-continuity/`、`domains/c3-generation-engine/human-ai-oversight-handoff-accountability-continuity/` 和 `domains/c3-generation-engine/ai-resource-cost-latency-budget-continuity/`：第七十九波正式研究域，分别承载 AI 评测基准有效性、红队对抗测试、事故报告部署后监控、数据谱系污染漂移、合成数据验证、模型供应链发布、agent 工具权限沙箱、人机监督交接问责和 AI 资源成本延迟预算。
- `domains/c4-conversion-channel/semiconductor-manufacturing-metrology-continuity/`、`domains/c6-local-unlocking/semiconductor-advanced-packaging-continuity/`、`domains/c6-local-unlocking/chip-design-eda-verification-ip-continuity/`、`domains/c3-generation-engine/ai-hardware-accelerator-performance-continuity/`、`domains/c4-conversion-channel/data-center-cooling-water-thermal-continuity/`、`domains/c5-ecological-substrate/large-load-grid-interconnection-transmission-continuity/`、`domains/c5-ecological-substrate/grid-scale-energy-storage-flexibility-continuity/`、`domains/c2-source-maintenance/advanced-nuclear-energy-safety-generation-continuity/`、`domains/c5-ecological-substrate/undersea-cable-internet-backbone-continuity/` 和 `domains/c3-generation-engine/satellite-communications-spectrum-orbit-continuity/`：第八十波正式研究域，分别承载半导体制造计量、先进封装、芯片设计 EDA 验证 IP、AI 加速器性能、数据中心冷却水热、大型负载并网输电、电网储能灵活性、先进核能安全发电、海底光缆骨干和卫星通信频谱轨道这些计算、能源与连接底座。
- `domains/c6-local-unlocking/cardiac-arrest-cpr-defibrillation-continuity/`、`domains/c2-source-maintenance/sepsis-shock-early-recognition-resuscitation-continuity/`、`domains/c2-source-maintenance/trauma-system-hemorrhage-control-continuity/`、`domains/c2-source-maintenance/intensive-care-organ-support-delirium-continuity/`、`domains/c2-source-maintenance/mechanical-ventilation-respiratory-failure-continuity/`、`domains/c6-local-unlocking/ecmo-extracorporeal-life-support-continuity/`、`domains/c2-source-maintenance/acute-kidney-injury-renal-replacement-continuity/`、`domains/c2-source-maintenance/transfusion-blood-management-hemorrhage-continuity/`、`domains/c6-local-unlocking/overdose-poisoning-reversal-toxicology-continuity/` 和 `domains/c2-source-maintenance/burn-injury-critical-care-rehabilitation-continuity/`：第八十一波正式研究域，分别承载心脏骤停 CPR/除颤、脓毒症休克早识别复苏、创伤出血控制、ICU 器官支持谵妄、机械通气呼吸衰竭、ECMO/ECLS、急性肾损伤肾脏替代、输血血液管理、过量/中毒逆转和烧伤重症康复这些急性死亡边界。
- `domains/c2-source-maintenance/acute-coronary-syndrome-reperfusion-continuity/`、`domains/c2-source-maintenance/acute-heart-failure-decompensation-continuity/`、`domains/c6-local-unlocking/cardiac-arrhythmia-syncope-decompensation-continuity/`、`domains/c6-local-unlocking/venous-thromboembolism-pulmonary-embolism-continuity/`、`domains/c2-source-maintenance/hypertensive-crisis-end-organ-risk-continuity/`、`domains/c2-source-maintenance/diabetic-hyperglycemic-hypoglycemic-crisis-continuity/`、`domains/c2-source-maintenance/anaphylaxis-allergic-emergency-continuity/`、`domains/c2-source-maintenance/asthma-copd-exacerbation-airway-continuity/`、`domains/c2-source-maintenance/acute-gastrointestinal-bleeding-endoscopy-continuity/` 和 `domains/c5-ecological-substrate/obstetric-emergency-hemorrhage-hypertension-continuity/`：第八十二波正式研究域，分别承载急性冠脉综合征再灌注、急性心衰失代偿、心律失常/晕厥、VTE/肺栓塞、高血压危象、糖尿病高低血糖危象、过敏性休克、哮喘/COPD 急性加重、急性消化道出血和产科出血/高血压急症。
- `domains/c6-local-unlocking/hypertension-detection-control-continuity/`、`domains/c6-local-unlocking/lipid-atherosclerosis-risk-management-continuity/`、`domains/c2-source-maintenance/prediabetes-diabetes-prevention-continuity/`、`domains/c2-source-maintenance/obesity-adiposity-metabolic-risk-continuity/`、`domains/c6-local-unlocking/tobacco-nicotine-cessation-continuity/`、`domains/c6-local-unlocking/alcohol-use-risk-reduction-continuity/`、`domains/c2-source-maintenance/chronic-kidney-disease-screening-progression-continuity/`、`domains/c2-source-maintenance/cancer-screening-early-detection-continuity/`、`domains/c2-source-maintenance/osteoporosis-fracture-prevention-bone-health-continuity/` 和 `domains/c5-ecological-substrate/fall-risk-prevention-home-safety-continuity/`：第八十三波正式研究域，分别承载高血压检测控制、血脂/动脉粥样硬化风险管理、糖尿病前期预防、肥胖/脂肪代谢风险、烟草尼古丁戒断、酒精风险降低、CKD 筛查进展、癌症筛查早诊、骨质疏松骨折预防和跌倒/家居安全预防。
- `domains/c4-conversion-channel/sleep-disordered-breathing-screening-treatment-continuity/`、`domains/c6-local-unlocking/chronic-insomnia-cbti-access-continuity/`、`domains/c6-local-unlocking/narcolepsy-daytime-sleepiness-continuity/`、`domains/c6-local-unlocking/idiopathic-hypersomnia-excessive-sleepiness-continuity/`、`domains/c6-local-unlocking/restless-legs-periodic-limb-movement-sleep-continuity/`、`domains/c6-local-unlocking/circadian-rhythm-sleep-wake-disorder-continuity/`、`domains/c6-local-unlocking/shift-work-long-hours-fatigue-continuity/`、`domains/c6-local-unlocking/parasomnia-sleepwalking-behavior-safety-continuity/`、`domains/c6-local-unlocking/sexual-health-sti-prevention-continuity/`、`domains/c6-local-unlocking/hiv-testing-prep-prevention-continuity/`、`domains/c2-source-maintenance/chronic-viral-hepatitis-screening-liver-protection-continuity/`、`domains/c6-local-unlocking/contraception-family-planning-access-continuity/`、`domains/c3-generation-engine/menstrual-health-cycle-literacy-continuity/`、`domains/c6-local-unlocking/perimenopause-menopause-midlife-health-continuity/`、`domains/c6-local-unlocking/pelvic-floor-continence-function-continuity/` 和 `domains/c2-source-maintenance/skin-cancer-uv-protection-early-detection-continuity/`：第八十四波和第 128 波正式研究域，分别承载睡眠呼吸障碍、慢性失眠/CBT-I 可及、发作性睡病、特发性嗜睡、RLS/周期性肢动、昼夜节律睡眠-觉醒障碍、轮班长工时疲劳、异态睡眠/梦游行为安全、性健康/STI、HIV 检测/PrEP、慢性病毒性肝炎、避孕家庭计划、月经健康、更年期、盆底控尿控便和皮肤癌/UV 防护。
- `domains/c5-ecological-substrate/workplace-fall-protection-height-safety-continuity/`、`domains/c5-ecological-substrate/hazardous-energy-lockout-tagout-continuity/`、`domains/c6-local-unlocking/machine-guarding-amputation-prevention-continuity/`、`domains/c6-local-unlocking/powered-industrial-truck-forklift-safety-continuity/`、`domains/c6-local-unlocking/confined-space-entry-atmospheric-hazard-continuity/` 和 `domains/c2-source-maintenance/bloodborne-pathogens-sharps-injury-worker-continuity/`：第 129 波正式研究域，分别承载工作场所高处坠落、危险能量锁定挂牌、机器防护截肢预防、叉车/工业车辆安全、受限空间大气危害和血源性病原体锐器伤工作者连续性。
- `domains/c6-local-unlocking/trenching-excavation-cave-in-worker-continuity/`、`domains/c6-local-unlocking/crane-derrick-hoist-rigging-suspended-load-continuity/`、`domains/c5-ecological-substrate/occupational-electrical-shock-arc-flash-continuity/`、`domains/c6-local-unlocking/welding-cutting-brazing-fume-fire-continuity/`、`domains/c6-local-unlocking/respirable-crystalline-silica-dust-worker-continuity/` 和 `domains/c6-local-unlocking/demolition-structural-collapse-debris-continuity/`：第 130 波正式研究域，分别承载沟槽开挖坍塌、起重吊装悬吊载荷、职业电击电弧闪爆、焊接切割烟尘火灾、可吸入结晶硅尘和拆除坍塌碎片施工/工业现场特定致命机制连续性。
- `domains/c2-source-maintenance/chronic-pain-functional-restoration-continuity/`、`domains/c2-source-maintenance/low-back-pain-spine-function-continuity/`、`domains/c6-local-unlocking/osteoarthritis-joint-function-continuity/`、`domains/c6-local-unlocking/autoimmune-rheumatic-disease-inflammatory-burden-continuity/`、`domains/c6-local-unlocking/inflammatory-bowel-disease-digestive-continuity/`、`domains/c2-source-maintenance/chronic-liver-disease-masld-mash-continuity/`、`domains/c2-source-maintenance/thyroid-disease-endocrine-function-continuity/`、`domains/c2-source-maintenance/adrenal-insufficiency-cortisol-stress-response-continuity/`、`domains/c2-source-maintenance/cushing-syndrome-hypercortisolism-metabolic-bone-continuity/`、`domains/c2-source-maintenance/pituitary-disorders-hormone-axis-continuity/`、`domains/c2-source-maintenance/acromegaly-growth-hormone-cardiometabolic-continuity/`、`domains/c2-source-maintenance/hypogonadism-testosterone-sex-hormone-continuity/`、`domains/c2-source-maintenance/primary-ovarian-insufficiency-hormone-fertility-continuity/`、`domains/c2-source-maintenance/iron-deficiency-anemia-oxygen-carrying-continuity/`、`domains/c2-source-maintenance/asthma-copd-maintenance-control-continuity/` 和 `domains/c2-source-maintenance/allergic-atopic-disease-immunologic-burden-continuity/`：第八十五波和第 127 波正式研究域，分别承载慢性疼痛、腰背痛、骨关节炎、自身免疫风湿病、炎症性肠病、MASLD/MASH 慢性肝病、甲状腺疾病、肾上腺不足、库欣综合征、垂体疾病、肢端肥大症、性腺功能低下、POI、铁缺乏贫血、哮喘/COPD 长期控制和过敏/特应性疾病。
- `domains/c6-local-unlocking/parkinsons-disease-movement-control-continuity/`、`domains/c6-local-unlocking/multiple-sclerosis-demyelination-function-continuity/`、`domains/c2-source-maintenance/amyotrophic-lateral-sclerosis-motor-neuron-continuity/`、`domains/c2-source-maintenance/huntington-disease-genetic-neurodegeneration-continuity/`、`domains/c2-source-maintenance/spinal-muscular-atrophy-motor-neuron-continuity/`、`domains/c6-local-unlocking/muscular-dystrophy-progressive-weakness-continuity/`、`domains/c2-source-maintenance/myasthenia-gravis-neuromuscular-junction-continuity/`、`domains/c6-local-unlocking/spinal-cord-injury-paralysis-secondary-complications-continuity/`、`domains/c5-ecological-substrate/me-cfs-post-exertional-energy-limitation-continuity/` 和 `domains/c2-source-maintenance/long-covid-post-acute-infection-continuity/`：第八十六波正式研究域，分别承载帕金森病、多发性硬化、ALS、亨廷顿病、脊髓性肌萎缩症、肌营养不良、重症肌无力、脊髓损伤、ME/CFS 和 Long COVID。
- `domains/c2-source-maintenance/breast-cancer-screening-treatment-survivorship-continuity/`、`domains/c2-source-maintenance/colorectal-cancer-screening-treatment-continuity/`、`domains/c2-source-maintenance/lung-cancer-screening-treatment-continuity/`、`domains/c2-source-maintenance/prostate-cancer-screening-treatment-continuity/`、`domains/c2-source-maintenance/cervical-cancer-hpv-prevention-screening-continuity/`、`domains/c2-source-maintenance/ovarian-cancer-symptom-detection-treatment-continuity/`、`domains/c2-source-maintenance/pancreatic-cancer-high-risk-detection-treatment-continuity/`、`domains/c2-source-maintenance/liver-cancer-cirrhosis-surveillance-treatment-continuity/`、`domains/c2-source-maintenance/childhood-cancer-treatment-survivorship-continuity/` 和 `domains/c2-source-maintenance/cancer-survivorship-late-effects-continuity/`：第八十七波正式研究域，分别承载乳腺癌、结直肠癌、肺癌、前列腺癌、宫颈癌、卵巢癌、胰腺癌、肝癌、儿童癌症和癌症幸存者晚期效应。
- `domains/c2-source-maintenance/dental-caries-prevention-restoration-continuity/`、`domains/c6-local-unlocking/periodontal-disease-systemic-inflammation-continuity/`、`domains/c6-local-unlocking/tooth-loss-prosthodontic-chewing-continuity/`、`domains/c2-source-maintenance/dental-pain-emergency-infection-continuity/`、`domains/c2-source-maintenance/oral-cancer-mucosal-lesion-early-detection-continuity/`、`domains/c2-source-maintenance/pediatric-oral-health-development-continuity/`、`domains/c2-source-maintenance/geriatric-long-term-care-oral-health-continuity/`、`domains/c2-source-maintenance/dental-care-access-insurance-workforce-continuity/`、`domains/c2-source-maintenance/xerostomia-salivary-function-oral-medication-continuity/` 和 `domains/c2-source-maintenance/temporomandibular-orofacial-pain-jaw-function-continuity/`：第八十八波正式研究域，分别承载龋病、牙周病、缺牙修复咀嚼、牙痛急性感染、口腔癌早期识别、儿童口腔、老年长期照护口腔、牙科服务可及性、口干唾液功能和颞下颌/口颌面痛。
- `domains/c6-local-unlocking/outbreak-case-investigation-contact-tracing-continuity/`、`domains/c5-ecological-substrate/isolation-quarantine-work-school-continuity/`、`domains/c4-conversion-channel/community-testing-screening-access-continuity/`、`domains/c6-local-unlocking/vaccination-campaign-booster-delivery-continuity/`、`domains/c6-local-unlocking/mask-respirator-source-control-fit-access-continuity/`、`domains/c6-local-unlocking/indoor-ventilation-filtration-outbreak-control-continuity/`、`domains/c5-ecological-substrate/school-workplace-outbreak-operations-continuity/`、`domains/c4-conversion-channel/healthcare-surge-triage-capacity-continuity/`、`domains/c6-local-unlocking/medical-countermeasure-stockpile-distribution-continuity/` 和 `domains/c5-ecological-substrate/wastewater-pathogen-surveillance-early-warning-continuity/`：第一百波正式研究域，分别承载传染病暴发中的病例调查接触追踪、隔离检疫工作学校、社区检测筛查、疫苗行动加强针递送、口罩呼吸防护、室内通风过滤、学校工作场所运营、医疗挤兑分诊容量、医疗对策储备分发和污水病原体早期预警。
- `domains/c6-local-unlocking/chemical-release-shelter-evacuation-continuity/`、`domains/c5-ecological-substrate/community-right-to-know-chemical-risk-disclosure-continuity/`、`domains/c5-ecological-substrate/hazmat-incident-command-emergency-response-continuity/`、`domains/c6-local-unlocking/industrial-process-safety-management-continuity/`、`domains/c3-generation-engine/toxic-plume-air-monitoring-risk-communication-continuity/`、`domains/c6-local-unlocking/hazwoper-responder-ppe-safety-continuity/`、`domains/c6-local-unlocking/decontamination-exposure-triage-continuity/`、`domains/c5-ecological-substrate/hazardous-materials-transportation-erg-continuity/`、`domains/c6-local-unlocking/oil-spill-hazardous-release-response-recovery-continuity/` 和 `domains/c6-local-unlocking/battery-thermal-runaway-fire-hazard-continuity/`：第一百零一波正式研究域，分别承载危险材料事故中的化学释放避险撤离、社区风险知情披露、HazMat 指挥、工业过程安全、有毒羽流空气监测、响应者 PPE、暴露后去污分诊、危险品运输 ERG、油污危险释放恢复和电池热失控火灾风险。
- `domains/c3-generation-engine/severe-weather-watch-warning-risk-communication-continuity/`、`domains/c5-ecological-substrate/river-flash-flood-warning-evacuation-continuity/`、`domains/c5-ecological-substrate/hurricane-storm-surge-evacuation-shelter-continuity/`、`domains/c5-ecological-substrate/tornado-warning-safe-room-shelter-continuity/`、`domains/c5-ecological-substrate/winter-storm-cold-exposure-power-continuity/`、`domains/c5-ecological-substrate/drought-water-restriction-household-health-continuity/`、`domains/c5-ecological-substrate/landslide-mudslide-debris-flow-warning-continuity/`、`domains/c2-source-maintenance/wildfire-smoke-clean-air-respiratory-continuity/`、`domains/c6-local-unlocking/thunderstorm-lightning-outdoor-safety-continuity/` 和 `domains/c5-ecological-substrate/coastal-flooding-erosion-inundation-continuity/`：第一百零二波正式研究域，分别承载强天气预警沟通、河流/山洪预警撤离、飓风风暴潮撤离避难、龙卷风短时避险、冬季风暴寒冷停电、干旱用水与健康、滑坡泥石流预警、野火烟雾清洁空气、雷暴闪电户外安全和海岸洪水侵蚀淹没连续性。
- `domains/c6-local-unlocking/mosquito-bite-arbovirus-prevention-continuity/`、`domains/c6-local-unlocking/tick-bite-lyme-rickettsial-prevention-continuity/`、`domains/c6-local-unlocking/rabies-exposure-bite-pep-continuity/`、`domains/c5-ecological-substrate/dog-bite-community-injury-prevention-continuity/`、`domains/c6-local-unlocking/rodent-infestation-hantavirus-plague-continuity/`、`domains/c5-ecological-substrate/bed-bug-infestation-sleep-housing-continuity/`、`domains/c6-local-unlocking/venomous-bites-stings-envenomation-continuity/`、`domains/c6-local-unlocking/reptile-amphibian-backyard-poultry-salmonella-continuity/`、`domains/c5-ecological-substrate/lice-scabies-school-shelter-infestation-continuity/` 和 `domains/c6-local-unlocking/pesticide-label-exposure-poison-control-continuity/`：第一百零三波正式研究域，分别承载蚊虫叮咬、蜱虫叮咬、狂犬病暴露、犬咬伤、鼠害、床虱、毒咬蜇伤、爬宠家禽沙门氏菌、虱疥和农药标签中毒连接连续性。
- `domains/c2-source-maintenance/pollen-allergen-asthma-outdoor-activity-continuity/`、`domains/c6-local-unlocking/poison-ivy-oak-sumac-urushiol-exposure-continuity/`、`domains/c5-ecological-substrate/harmful-algal-bloom-cyanotoxin-water-recreation-continuity/`、`domains/c6-local-unlocking/toxic-mushroom-foraging-poisoning-continuity/`、`domains/c5-ecological-substrate/poisonous-plant-childcare-household-exposure-continuity/`、`domains/c6-local-unlocking/invasive-species-human-health-access-continuity/`、`domains/c5-ecological-substrate/mycotoxin-food-crop-storage-safety-continuity/`、`domains/c5-ecological-substrate/recreational-water-illness-beach-lake-access-continuity/`、`domains/c5-ecological-substrate/shellfish-biotoxin-harmful-algal-bloom-food-continuity/` 和 `domains/c5-ecological-substrate/landscaping-horticulture-worker-equipment-injury-continuity/`：第一百零四波正式研究域，分别承载花粉过敏哮喘、漆酚植物、有害藻华蓝藻毒素、野生蘑菇、有毒植物、入侵物种、霉菌毒素、休闲水病原、贝类毒素和园林园艺户外工伤连续性。
- `domains/c2-source-maintenance/contact-lens-hygiene-eye-infection-continuity/`、`domains/c2-source-maintenance/hearing-aid-maintenance-battery-access-continuity/`、`domains/c6-local-unlocking/menstrual-product-access-safety-continuity/`、`domains/c5-ecological-substrate/incontinence-absorbent-product-supply-dignity-continuity/`、`domains/c2-source-maintenance/diabetic-therapeutic-footwear-offloading-continuity/` 和 `domains/c6-local-unlocking/compression-garment-lymphedema-venous-continuity/`：第一百零五波正式研究域，分别承载隐形眼镜卫生、助听设备维护、月经用品、失禁吸收用品、糖尿病治疗鞋/卸载和压迫用品这些贴身设备与耗材执行连续性。
- `domains/c2-source-maintenance/eyeglasses-prescription-repair-replacement-continuity/`、`domains/c6-local-unlocking/wheelchair-scooter-battery-repair-access-continuity/`、`domains/c6-local-unlocking/walker-cane-crutch-fit-maintenance-continuity/`、`domains/c6-local-unlocking/prosthetic-limb-orthotic-fit-repair-continuity/`、`domains/c5-ecological-substrate/cpap-pap-device-mask-supply-power-continuity/` 和 `domains/c5-ecological-substrate/fall-detection-emergency-response-device-continuity/`：第一百零六波正式研究域，分别承载眼镜修理替换、轮椅/代步车电池维修、助行器具维护、假肢矫形适配维修、PAP 设备耗材供电和跌倒检测响应设备这些个人辅助设备运行连续性。
- `domains/c5-ecological-substrate/private-well-water-testing-treatment-continuity/`、`domains/c5-ecological-substrate/household-water-treatment-filter-maintenance-continuity/`、`domains/c5-ecological-substrate/lead-service-line-lead-copper-drinking-water-continuity/`、`domains/c6-local-unlocking/premise-plumbing-backflow-cross-connection-continuity/`、`domains/c6-local-unlocking/septic-system-maintenance-sewage-backup-continuity/` 和 `domains/c5-ecological-substrate/basement-flooding-sump-pump-moisture-recovery-continuity/`：第一百零七波正式研究域，分别承载私人井水检测处理、家庭滤水维护、铅铜饮水管线、建筑回流交叉连接、化粪池污水回流和地下室进水潮湿恢复这些家庭水与污水执行连续性。
- `domains/c5-ecological-substrate/residential-electrical-wiring-outlet-safety-continuity/`、`domains/c5-ecological-substrate/home-heating-equipment-chimney-vent-maintenance-continuity/`、`domains/c3-generation-engine/home-cooling-heat-pump-air-conditioning-maintenance-continuity/`、`domains/c6-local-unlocking/natural-gas-propane-leak-shutoff-continuity/`、`domains/c6-local-unlocking/thermostat-temperature-control-thermal-comfort-continuity/` 和 `domains/c3-generation-engine/weatherization-insulation-air-sealing-thermal-envelope-continuity/`：第一百零八波正式研究域，分别承载住宅电气线路插座、家庭供暖烟囱排气、家庭制冷热泵维护、天然气/丙烷泄漏关断、温控器室温控制和天气化保温围护结构这些家庭能源与热安全执行连续性。
- `domains/c6-local-unlocking/residential-solid-waste-collection-bin-sanitation-continuity/`、`domains/c5-ecological-substrate/household-hazardous-waste-chemical-disposal-continuity/`、`domains/c5-ecological-substrate/home-sharps-medical-waste-disposal-continuity/`、`domains/c6-local-unlocking/e-waste-battery-recycling-disposal-continuity/`、`domains/c5-ecological-substrate/food-scrap-composting-pest-odor-continuity/` 和 `domains/c6-local-unlocking/illegal-dumping-litter-neighborhood-sanitation-continuity/`：第一百零九波正式研究域，分别承载住宅固废收运垃圾桶卫生、家庭危险废物化学处置、家庭锐器医疗废物处置、电子废弃物电池回收、厨余堆肥害虫气味和非法倾倒邻里卫生这些家庭废弃物与处置执行连续性。
- `domains/c3-generation-engine/home-hvac-filter-maintenance-indoor-air-continuity/`、`domains/c3-generation-engine/portable-air-cleaner-room-filtration-continuity/`、`domains/c3-generation-engine/cooking-ventilation-range-hood-indoor-air-continuity/`、`domains/c5-ecological-substrate/home-humidity-dehumidifier-moisture-control-continuity/`、`domains/c5-ecological-substrate/household-dust-allergen-source-control-continuity/` 和 `domains/c5-ecological-substrate/household-voc-fragrance-product-emission-continuity/`：第一百一十波正式研究域，分别承载 HVAC 滤网维护、便携房间过滤、烹饪排风、家庭湿度水分控制、灰尘过敏原源控制和 VOC/香氛/产品释放这些家庭室内空气执行连续性。
- `domains/c5-ecological-substrate/home-clutter-pathway-trip-fall-continuity/`、`domains/c5-ecological-substrate/household-cord-cable-trip-entanglement-continuity/`、`domains/c5-ecological-substrate/home-shelving-cabinet-storage-stability-continuity/`、`domains/c5-ecological-substrate/household-ladder-step-stool-reach-task-continuity/`、`domains/c5-ecological-substrate/home-office-workstation-ergonomics-continuity/` 和 `domains/c6-local-unlocking/toy-small-parts-choking-ingestion-continuity/`：第一百一十一波正式研究域，分别承载通道杂物绊倒、家庭线缆绊倒缠绕、货架柜体储物稳定、梯凳高处任务、居家办公工位工效和玩具小零件窒息误吞这些家庭物理秩序与物品访问执行连续性。
- `domains/c5-ecological-substrate/home-utility-shutoff-location-labeling-continuity/`、`domains/c5-ecological-substrate/household-circuit-breaker-panel-labeling-continuity/`、`domains/c5-ecological-substrate/home-water-valve-plumbing-labeling-continuity/`、`domains/c4-conversion-channel/household-equipment-serial-model-recall-record-continuity/`、`domains/c5-ecological-substrate/home-service-provider-emergency-contact-directory-continuity/` 和 `domains/c5-ecological-substrate/household-operating-map-handoff-continuity/`：第一百一十二波正式研究域，分别承载家庭公用设施关断位置标识、断路器面板标签、水路阀门标签、家庭设备型号召回记录、家庭服务联系人目录和家庭运行地图交接这些家庭运行元数据与交接连续性。
- `domains/c6-local-unlocking/municipal-311-service-request-continuity/`、`domains/c6-local-unlocking/streetlight-outage-nighttime-visibility-continuity/`、`domains/c6-local-unlocking/sidewalk-curb-ramp-maintenance-access-continuity/`、`domains/c6-local-unlocking/snow-ice-sidewalk-winter-access-continuity/`、`domains/c6-local-unlocking/street-tree-branch-hazard-shade-maintenance-continuity/` 和 `domains/c5-ecological-substrate/storm-drain-catch-basin-local-flooding-continuity/`：第一百一十三波正式研究域，分别承载市政 311 服务请求、路灯夜间可见性、人行道/路缘坡道维护、雪冰冬季通行、街道树木维护和雨水口局部内涝这些邻里公共空间维护与地方服务请求执行连续性。
- `domains/c6-local-unlocking/child-care-availability-affordability-continuity/`、`domains/c6-local-unlocking/child-care-licensing-health-safety-continuity/`、`domains/c5-ecological-substrate/child-care-subsidy-ccdf-payment-continuity/`、`domains/c6-local-unlocking/head-start-early-head-start-family-support-continuity/`、`domains/c6-local-unlocking/early-intervention-idea-part-c-developmental-services-continuity/` 和 `domains/c3-generation-engine/out-of-school-time-afterschool-summer-learning-continuity/`：第一百一十四波正式研究域，分别承载托育供给费用、许可健康安全、CCDF 补贴支付、Head Start / Early Head Start、IDEA Part C 早期干预和课外/暑期学习照护这些早期儿童照护执行连续性。
- `reference/research-model-visualization-toolkit.md`：沉淀科研论文阅读、文献脊梁、模型工具、可视化标准和 Human Infra 定量页面实现路线。
- `reference/source-card-system.md`：定义论文、书籍、工具、案例、标准和数据集进入项目之前的资料卡片制度。
- `reference/domain-map.md`：定义根项目与子域的边界、迁移切片、主动不做和验证点。
- `reference/ethics-and-safety-boundaries.md`：定义医疗、组织、去具身中枢、记忆编辑和数据证据边界。
- `reference/evidence-policy.md`：定义证据、解释、主张、推测和决策的分层规则。
- `reference/source-management.md`：定义 source notes、外部数据和稳定文档之间的流转规则。
- `reference/document-lifecycle.md`：定义文档从 source 到 stable、superseded、archived 的生命周期。
- `reference/repository-standards.md`：记录本仓库采用的标准结构、根文件和调研来源。
- `reference/review-checklists.md`：提供文档、证据、安全、域边界和数据脚本审查清单。
- `how-to/add-domain.md`：说明新增子域的步骤和停止条件。
- `how-to/add-source-note.md`：说明新增 source note 的步骤和规则。
- `how-to/run-quality-checks.md`：说明如何运行本地质量检查。
- `how-to/share-human-infra.md`：说明如何对外介绍 Human Infra、复用短推文模板并保持传播边界。
- `source-notes/`：保存最新资料原文或轻整理版本，供后续提炼，不直接作为产品说明入口。
- `source-notes/README.md`：说明原始资料归档的文件职责和使用规则。
- `source-notes/core-literature/`：保存 Human Infra 谱系论文集的下载清单、核心 Source Card 草案、论文解读报告和缓存边界说明；原文缓存留在 `.research/literature/`。
- `source-notes/2026-06-28-effective-immortality-flywheel-automated-research-run.md`：记录有效永生飞轮第一轮自动化科研流程、文献脊梁、发现和下一步任务。
- `source-notes/2026-06-28-effective-immortality-flywheel-derivation-package.md`：保存有效永生飞轮公式推导包，冻结不变量、假设、符号、推导图、主公式、边界和开放风险。
- `source-notes/2026-06-28-effective-immortality-flywheel-evidence-matrix.md`：保存有效永生飞轮证据矩阵，把主链路拆成可检验边，并记录候选来源、证据角色、断裂条件和下一步模型任务。
- `source-notes/2026-06-28-effective-immortality-flywheel-source-cards.md`：保存有效永生飞轮第一批来源卡片，服务后续论文扩写、模型变量和 Web 可视化。
- `source-notes/2026-06-29-metric-redshift-recursive-waiting-revision-notes.md`：保存度规红移递归等待假设论文页 v0.2 优化依据、来源分层和下一步科研任务。
- `source-notes/2026-06-29-controllable-metric-waiting-room-hypothesis-revision-notes.md`：保存可控度规等待室假设论文页收口记录，包括研究对象、toy NCG 推导、场景比较、引用语境、预提交审查和覆盖审计。
- `templates/`：保存决策记录、子域 README、research card、source note 和 reference 文档模板。

## 依赖关系

- `README.md` 和根 `AGENTS.md` 依赖本目录的稳定文档描述总项目。
- `domains/*/README.md` 可引用本目录的上位原则，但不能把自身职责推回 `docs/`。
- `source-notes/` 只向稳定文档提供资料来源，不反向决定架构。

## 维护规则

- 新的跨域原则、伦理边界、域地图变更写入本目录。
- 单一子域的产品、数据源、脚本说明写入对应 `domains/*/`。
- 原始资料进入 `source-notes/` 前必须改成语义化文件名。
- 稳定结论应从 `source-notes/` 提炼出来，避免长期以临时资料名作为知识入口。
- 新增重复类型文档时优先使用 `templates/`，避免每次重新发明结构。
